### ISSUE TITLE
Install fail

### ISSUE THREAD

**Issue by Martin730913** [composer/windows-setup#104]
When I install in WIN10,it sugggests following errors. What should  I do to solve this problem.

The Composer installer script was not successful [exit code 1].

Script Output:
The "https://getcomposer.org/versions" file could not be downloaded: SSL: 远程主机强迫关闭了一个现有的连接。
send of 24 bytes failed with errno=10054 远程主机强迫关闭了一个现有的连接。
send of 23 bytes failed with errno=10054 远程主机强迫关闭了一个现有的连接。
send of 72 bytes failed with errno=10054 远程主机强迫关闭了一个现有的连接。
send of 2 bytes failed with errno=10054 远程主机强迫关闭了一个现有的连接。
failed to open stream: HTTP request failed!

**Comment by Martin730913** [comment]
> @Martin730913 Please provide log file, as per the new issue instructions:
> https://github.com/composer/windows-setup/issues/new
This is the log file
[Setup Log 2019-10-13 #001.txt](https://github.com/composer/windows-setup/files/3737019/Setup.Log.2019-10-13.001.txt)

**Comment by johnstevenson** [comment]
Thanks for the log. You are using an old version of PHP (5.4.45) that does not support modern TLS protocols for https transport. PHP version 5.5.0 and upwards are fine.

If you are really stuck with using a 5.4 version, then you need to:

- disable the open_ssl extension in your php.ini
- ignore Composer-Setup.exe's request to update your php.ini

When composer is installed, you then need to configure it to run without TLS:

```
composer config -g disable-tls true
```

This is really not recommended.

**Comment by Martin730913** [comment]
> Thanks for the log. You are using an old version of PHP (5.4.45) that does not support modern TLS protocols for https transport. PHP version 5.5.0 and upwards are fine.
> 
> If you are really stuck with using a 5.4 version, then you need to:
> 
> * disable the open_ssl extension in your php.ini
> * ignore Composer-Setup.exe's request to update your php.ini
> 
> When composer is installed, you then need to configure it to run without TLS:
> 
> ```
> composer config -g disable-tls true
> ```
> 
> This is really not recommended.

Thank you!
