### ISSUE TITLE
Error while installing composer on windows 10

### ISSUE THREAD

**Issue by henpong** [composer/windows-setup#108]
The Composer installer script was not successful [exit code 1].

OpenSSL failed with a 'certificate verify failed' error. This indicates a problem with the Certificate Authority file(s) on your system, which may be out of date.

Certificate location [from openssl.cafile ini setting]:
C:\xampp\apache\bin\curl-ca-bundle.crt

The php.ini used by your command-line PHP is: C:\xampp\php\php.ini

Script Output:
The "https://getcomposer.org/versions" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
Failed to enable crypto
failed to open stream: operation failed

**Comment by johnstevenson** [comment]
Could you please supply a log, as per the new issue instructions: https://github.com/composer/windows-setup/issues/new

Thanks.

**Comment by henpong** [comment]
Hello boss,

This is the error I get when I try to install the composer.

ERROR LOG:

The Composer installer script was not successful [exit code 1].

OpenSSL failed with a 'certificate verify failed' error. This indicates a
problem with the Certificate Authority file(s) on your system, which may be
out of date.

Certificate location [from openssl.cafile ini setting]:
C:\xampp\apache\bin\curl-ca-bundle.crt

The php.ini used by your command-line PHP is: C:\xampp\php\php.ini

Script Output:
The "https://getcomposer.org/versions" file could not be downloaded: SSL
operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate
verify failed
Failed to enable crypto
failed to open stream: operation failed

Can you help me with the solution ?

Thank you
Rgards
Henry

**Comment by johnstevenson** [comment]
The installer creates a log file in your temp directory:

Composer-Setup creates a log file in your temp directory (C:\Users\...\AppData\Local\Temp), with a formatted filename: `Setup Log YYYY-MM-DD #nnn.txt`
Please include this file if you experienced a problem with the installation process. Review it first for any data that might be sensitive.

**Comment by henpong** [comment]
I can't locate the Setup Log file on my laptop

Where exactly is the log file?

Regards
Henry

**Comment by johnstevenson** [comment]
Well, if it is not where I've said it should be:

-  C:\Users\ your-username \AppData\Local\Temp

then open a command prompt and run: `echo %TEMP%`

**Comment by henpong** [comment]
Good morning Sir

I don't have \AppData\Local\Temp on my laptop so when I run %TEMP%, I get
an error message.

Kinly find it attached.

Regards
Henry

**Comment by johnstevenson** [comment]
I cannot see your error message! Try `echo %TMP%` instead. What is your Windows OS?

**Comment by dking3876** [comment]
As of dec 5, install was working but had been updated and using php 7.4. as of dec 6. the install now installs 7.2.15 and fails right after attempt o install 'chocolatey-core.extension (� 1.3.3)'

Failure notice is Unable to resolve dependency 'chocolatey-core.extension (� 1.3.3)'


UPDATE: THIS DID EVENTUALLY RESOLVE AND STARTED BEHAVING AS NORMAL. CHOCOLATY WAS HAVING ISSUES i ASSUME THIS RELATED TO THAT.

**Comment by johnstevenson** [comment]
@dking3876 You've hijacked someone else's issue (!) but thanks anyway.

Yes, it turns out that Chocolatey had a problem and wasn't resolving dependencies correctly if any had either a dot or a hyphen in their name (like chocolatey-core.extension, which is a dependency of the php package, which is a dependency of the composer package).

Without knowing your exact installation requirements, if you already have php installed (not necessarily from chocolatey) and it is in your path, then you can call `choco install -i -y composer` which bypasses the dependency bit. The `-i` param (must be on its own and not compounded with any other single-character params) means "ignore dependencies".

**Comment by johnstevenson** [comment]
Closing as no further info (regarding original issue)

**Comment by klorinczi** [comment]
I had "error:0A000086:SSL routines::certificate verify failed" error on Windows when installing Composer-Setup.exe.

After temporarily disabling the Avast/AVG antivirus, the "composer" installed successfully.

Solution source:
https://stackoverflow.com/a/79463726/4523359

**Comment by ZombieEater** [comment]
> I had "error:0A000086:SSL routines::certificate verify failed" error on Windows when installing Composer-Setup.exe.
> 
> After temporarily disabling the Avast/AVG antivirus, the "composer" installed successfully.
> 
> Solution source: https://stackoverflow.com/a/79463726/4523359

Worked for me!  Thanks @klorinczi
