### ISSUE TITLE
commposer installation error

### ISSUE THREAD

**Issue by devbytes12** [composer/windows-setup#110]
The Composer installer script was not successful [exit code 1].

Your proxy settings may be causing this error.

Script Output:
The "https://getcomposer.org/versions" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:1408F10B:SSL routines:ssl3_get_record:wrong version number
Failed to enable crypto
failed to open stream: operation failed

**Comment by johnstevenson** [comment]
A log file (as per the new issue template: https://github.com/composer/windows-setup/issues/new) would be useful.

**Comment by johnstevenson** [comment]
Closing as no further information provided.
