### ISSUE TITLE
Install fails if UOPZ extension is loaded

### ISSUE THREAD

**Issue by JakeQZ** [composer/windows-setup#111]
This is because by default UOPZ disables the `exit` opcode, so the desired exit code does not get passed from `installer.php` to the installer process (and `installer.php` may continue executing when it should have exited).

I guess a solution might be to call [`uopz_allow_exit`](https://www.php.net/manual/en/function.uopz-allow-exit.php) if the function exists.  Or add a note that the installer is not compatible with the UOPZ extension, or perhaps bail out somehow (without using `exit`) with an informative error message if `extension_loaded('uopz')`.

FWIW, I have attached a [log file](https://github.com/composer/windows-setup/files/4024157/composer-setup.log).

**Comment by johnstevenson** [comment]
Thanks for the report. I'll think about what the best option is (probably for the installer PHP script to bail out)

**Comment by johnstevenson** [comment]
Fixed in https://github.com/composer/windows-setup/commit/0f41ed858a3d538b71da621fdbe607f0dcc0675c
