### ISSUE TITLE
VirusTotal detection Composer-Setup.5.1.0.exe

### ISSUE THREAD

**Issue by n3amil** [composer/windows-setup#112]
Hi, the current installer .exe is detected by our antivirus (f-secure)
https://www.virustotal.com/gui/file/80422fef0ea310c0f565d6028f34010eeebc96a4edec3175156d85f4f0eeef10/detection
should we make a report for false positive? Currently were unable to install/download the .exe (same for chocolatey)

**Comment by johnstevenson** [comment]
Yawn, here we go again (F-Secure also detected a false positive for Composer-Setup.5.0.0.exe). 

Yes, please report it. You might perhaps also mention that they do not have a problem with the Chocolately package (composer.5.1.0.nupkg), which includes the embedded exe file: https://www.virustotal.com/gui/file/827b6bc31ab6499f8db3b38d8ade1192dc927bff98819febff79a9ee4d843347/detection

Which doesn't say much for their engine, considering that composer.5.1.0.nupkg is essentially a zipped archive containing an xml file and the exe!
