### ISSUE TITLE
Windows installer refuses to use XAMPP's PHP 7.4.5

### ISSUE THREAD

**Issue by PixievoltNo1** [composer/windows-setup#116]
I have a portable installation of XAMPP set up. Its php.exe is in my PATH. When I attempted to run Composer-Setup.exe, it correctly found php.exe, but then gave this error:

![Screenshot of Composer-Setup.exe](https://user-images.githubusercontent.com/272133/81369344-08374700-90a7-11ea-9296-921e638aa0f9.png)

As far as I can tell, php.exe is fine - most of Composer's manual installation instructions worked, as I described in composer/composer#8883, and I got this output from running `php.exe --version`:

```
PHP 7.4.5 (cli) (built: Apr 14 2020 16:17:34) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
```

**Comment by johnstevenson** [comment]
@PixievoltNo1 Could you supply a log file please, as per the instructions here: https://github.com/composer/windows-setup/issues/new

Thanks.

**Comment by PixievoltNo1** [comment]
Here it is: [Setup Log 2020-05-08 #001.txt](https://github.com/composer/windows-setup/files/4602344/Setup.Log.2020-05-08.001.txt)

**Comment by johnstevenson** [comment]
Thanks for the log. I downloaded xampp and was able to reproduce the error.

But when I ran `... \xampp\php\php.exe -v` from cmd, I got a whole bunch of error output, so you must have been running a different php, probably  `... \xampp\php\windowsXamppPhp\php`

Sorry, I don't know enough about xampp to know which php you should be running for CLI, but `... \xampp\php\php.exe` is configured incorrectly and results in a fatal error when it is run. Its configuration file at `... \xampp\php\php.ini` needs the following changes:

1. extension_dir = "\xampp\php\ext" should be `"ext"`
2. browscap = "xampp\php\extras\browscap.ini" should be `"extras\browscap.ini"` This is one that causes the fatal error.
3. All other "\xampp..." references should be suitably adjusted.
4. The folks at xampp probably need telling about this mess. 

The `... \xampp\php\windowsXamppPhp\php` doesn't have a php.ini (from a fresh download) so it won't have the required extensions enabled for Composer to work properly. ComposerSetup.exe will fix this as part of the installation.

**Comment by PixievoltNo1** [comment]
I have most certainly been using `\xampp\php\php.exe` to attempt all commands I have previously attempted. The default XAMPP configuration seems to be making the assumption it was placed at the root folder of a drive; I've been using it from the root folder of my USB drive. Perhaps since Composer's runphp.exe runs from a temp folder on `C:\`, it might somehow be causing driveless absolute paths to resolve to C paths, but the log file doesn't include enough information to conclude that's definitely the problem. I'll try some things in the near future to diagnose the problem further.

**Comment by johnstevenson** [comment]
ComposerSetup.exe runphp works fine running across drives. All it does is a CreateProcess using the full file path to php.exe

Perhaps PHP itself doesn't understand driveless absolute paths?

**Comment by johnstevenson** [comment]
@PixievoltNo1  You were correct - it was a problem running across drives and also because I hadn't realized that certain php.ini directives can cause a fatal error (failing to find `browscap.ini` in this instance).

So runphp.exe now invokes php without an ini file, so that it will correctly detect missing VC redistributables or other weirdness, as intended. Additionally, php is now executed from its containing folder and all scripts now use the full path from the temp directory.

Thanks for the report.
