### ISSUE TITLE
Cant install composer-setup.exe

### ISSUE THREAD

**Issue by riznisa** [composer/windows-setup#121]
the explanation while install composer
failed to open stream: HTTP request failed!
Some settings on your machine may cause stability issues with Composer.
If you encounter issues, try to change the following:

The Windows OneDrive folder is not supported on PHP versions below 7.2.23 and 7.3.10.
Upgrade your PHP (7.3.2) to use this location with Composer.

please tell me a solution

**Comment by johnstevenson** [comment]
Please supply a log file, as requested when you created this issue

**Comment by johnstevenson** [comment]
Closing as no further info forthcoming.
