### ISSUE TITLE
The command interpreter did not run correctly

### ISSUE THREAD

**Issue by JustSimonCZ** [composer/windows-setup#123]
Hello there!

I was trying to install the composer but the installation ended up with a error saying:
The command interpreter did not run correctly:
C:\WINDOWS\system32\cmd.exe

It changed the directory to...

Here is my log file:
[Setup Log 2020-09-02 #004.txt](https://github.com/composer/windows-setup/files/5162844/Setup.Log.2020-09-02.004.txt)
Also tried the sfc /scannow command in the cmd which ended with no issues found.

Thanks for the suggestions!

**Comment by johnstevenson** [comment]
Could you open up cmd.exe in your User directory then run the following 2  snippets and show me the output:

```
cd
cmd /c cd
```

Thanks.

**Comment by JustSimonCZ** [comment]
Well, if I´m doing it correctly, it does nothing.

**Comment by johnstevenson** [comment]
Sure, but I would like to see your output on screen. Your User folder is at `C:\Users\Šimon` but cmd.exe reports it at `C:\Users\ćimon`

**Comment by JustSimonCZ** [comment]
![cmd_bGoVVON2Tx](https://user-images.githubusercontent.com/70648562/92001278-c8bff500-ed3e-11ea-8fd8-692edda28c81.png)
Oh sorry, then here you go :)

**Comment by johnstevenson** [comment]
Thanks. The installer gets this output by writing it to a text file, then reading from that (which is the only way to do it in Inno Setup). So could you now try:

```
cmd /c cd >out.txt
```

and show me what is in `out.txt`

**Comment by JustSimonCZ** [comment]
[out.txt](https://github.com/composer/windows-setup/files/5163227/out.txt)
Well that is interresting. Now it shows the profile name badly.

**Comment by johnstevenson** [comment]
Thanks. It shows a different profile name `C:\Users\æimon` from the one reported in your log file `C:\Users\ćimon`, which as you pointed out is not the same as `C:\Users\Šimon`

Perhaps this is a codepage thing. Could you tell me what `chcp` outputs (although I believe this will be the input codepage used by cmd rather than the output codepage).

Or it could be an Inno thing, or me just buggering things up!

**Comment by JustSimonCZ** [comment]
There you go.
![cmd_xem8rwLRbj](https://user-images.githubusercontent.com/70648562/92006572-32db9880-ed45-11ea-9665-0b5e70c1800e.png)

**Comment by johnstevenson** [comment]
Thanks. I can replicate this now. 

If I create a directory named `Šimon` then it outputs `Šimon` on screen but writes `æimon` to file (using codepage 852) which Inno Setup then translates to `ćimon`. However switching to codepage 850 it writes `Simon` to file. However I am none the wiser.

I've changed the installer to just use the 8-character ascii temp directory name that Inno Setup creates for the comparison. Could you please give this a go:

[Composer-Setup.6.0.1.exe.zip](https://github.com/composer/windows-setup/files/5163641/Composer-Setup.6.0.1.exe.zip)

**Comment by JustSimonCZ** [comment]
Ok so the installation was succesful but now, when I try to open composer in cmd it shows this:
![cmd_dPvpvZyqiT](https://user-images.githubusercontent.com/70648562/92013437-109a4880-ed4e-11ea-8b3e-353b459986e5.png)
Could it be again the issue with the 'Š' letter?

**Comment by johnstevenson** [comment]
Hmm. Where did you install it. Run this in cmd:

```
where composer
```

or attach the latest log file.

**Comment by JustSimonCZ** [comment]
Ohh yes, I installed it in the wrong directory, sorry about that. I changed the directory and now it´s working perfectly. Thanks for the help!

**Comment by johnstevenson** [comment]
Could you explain where you installed it in order to get that error please.

**Comment by JustSimonCZ** [comment]
It was in C:\Users\Šimon\Appdata\Local\ComposerSetup\bin

**Comment by johnstevenson** [comment]
I can't replicate this (by installing into a directory at a path containing a `Šimon` folder).

Also, I don't understand your screen shot. It looks like you got no output when running `composer` (which can be called from any directory because it is on your path) and the error message `'Could' is not recognized as ...` looks like it is the result of calling `Could not open input file: @php`

Did you send the wrong image because it doesn't make any sense to me?

**Comment by JustSimonCZ** [comment]
No, the screenshot is correct. I can´t call the composer from any directory but only in the 
C:\Users\Šimon\Appdata\Local\ComposerSetup\bin directory. Here is the example:
![cmd_9x4MRXKwws](https://user-images.githubusercontent.com/70648562/92018984-33305f80-ed56-11ea-8c2a-597a57648bd4.png)

**Comment by johnstevenson** [comment]
I'm baffled. What does `where composer` report? Perhaps you could send me your last installation log. Thanks.

**Comment by JustSimonCZ** [comment]
![cmd_mm6LxkoEDY](https://user-images.githubusercontent.com/70648562/92021061-717b4e00-ed59-11ea-9fda-deae827bbaa9.png)
[Setup Log 2020-09-02 #008.txt](https://github.com/composer/windows-setup/files/5164057/Setup.Log.2020-09-02.008.txt)
Here it goes. Now I am baffled too xd.

**Comment by johnstevenson** [comment]
`C:\Windows\System32\composer.bat` shouldn't be there. Can you show me its contents please.

**Comment by JustSimonCZ** [comment]
![notepad_KdZw7qOBrv](https://user-images.githubusercontent.com/70648562/92026102-ca021980-ed60-11ea-8eba-59fbfe4569e8.png)
This is it.

**Comment by johnstevenson** [comment]
Good grief! At least that explains the error message that I could not understand. I suggest you delete that file, and try running `composer` from any directory again.

**Comment by JustSimonCZ** [comment]
Yes it now works from any directory finally. Thanks m8! I have no idea where that bat file came from. Have a nice day.
