### ISSUE TITLE
i cant install composer 

### ISSUE THREAD

**Issue by pmuthengi** [composer/windows-setup#126]
The Composer installer script was not successful [exit code 1].

OpenSSL failed with a 'certificate verify failed' error. This indicates a problem with the Certificate Authority file(s) on your system, which may be out of date.

Certificate location [from openssl.cafile ini setting]:
C:\xampp\apache\bin\curl-ca-bundle.crt

The php.ini used by your command-line PHP is: C:\xampp\php\php.ini

Script Output:
The "https://getcomposer.org/versions" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
Failed to enable crypto
failed to open stream: operation failed

**Comment by johnstevenson** [comment]
Your certificate data is out of date. Composer provides its own certificate bundle (data), so can either open your ini file (C:\xampp\php\php.ini) and comment out the openssl.cafile setting:

```
;openssl.cafile="C:\xampp\apache\bin\curl-ca-bundle.crt"
```
or if you need https on your local apache webserver, download an updated bundle from: https://curl.haxx.se/docs/caextract.html and save it to C:\xampp\apache\bin\curl-ca-bundle.crt
