### ISSUE TITLE
[V2] EVP_DigestSign could not be located in the dynamic link library libssh2.dll

### ISSUE THREAD

**Issue by ili101** [composer/windows-setup#127]
Download and extract PHP https://windows.php.net/download/
Run Composer-Setup.exe and select the php folder and next.
```
---------------------------
php.exe - Entry Point Not Found
---------------------------
The procedure entry point EVP_DigestSign could not be located in the dynamic link library C:\Program Files\php\libssh2.dll. 
---------------------------
OK   
---------------------------
```

**Comment by johnstevenson** [comment]
Please supply your log file:

  Composer-Setup creates a log file in your temp directory AppData\Local\Temp, with a formatted filename:
    Setup Log YYYY-MM-DD #nnn.txt
  Please include this file if you experienced a problem with the installation process. Review it first
  for any data that might be sensitive.

**Comment by ili101** [comment]
First error
```
---------------------------
php.exe - Entry Point Not Found
---------------------------
The procedure entry point EVP_DigestSign could not be located in the dynamic link library C:\Program Files\php\libssh2.dll. 
---------------------------
OK   
---------------------------
```
![image](https://user-images.githubusercontent.com/6960531/97182759-9c0be500-17a5-11eb-8234-27112d349795.png)

Then
```
The PHP exe file you specified did not run correctly:
C:\Program Files\php\php.exe

The php.ini used by your command-line PHP is: C:\Program Files\php\php.ini

A setting in your php.ini could be causing the problem: Either the 'extension_dir' value is incorrect or a dll does not exist.

Program Output:
PHP Warning:  PHP Startup: Unable to load dynamic library 'curl' (tried: ext\curl (The specified module could not be found.), ext\php_curl.dll (The specified procedure could not be found.)) in Unknown on line 0
```
![image](https://user-images.githubusercontent.com/6960531/97182773-a0380280-17a5-11eb-9480-e88b62601eda.png)

[Setup Log 2020-10-26 #005.txt](https://github.com/composer/windows-setup/files/5439236/Setup.Log.2020-10-26.005.txt)

**Comment by johnstevenson** [comment]
This has nothing to do with different versions of composer. This is because your php is not setup correctly. Could you please tell me what you downloaded from https://windows.php.net/download/

**Comment by ili101** [comment]
Looks like the curl error is from something I probably configured as I try on a new download and it's not showing.
But the ssh error is happening on the 2 versions I tried "VC15 x64 Thread Safe (2020-Sep-29 16:55:18)" and "VC15 x64 Non Thread Safe (2020-Sep-29 15:51:28)"

**Comment by johnstevenson** [comment]
Did you download and install the Visual C++ Redistributable for Visual Studio 2015-2019 https://aka.ms/vs/16/release/VC_redist.x64.exe ?

**Comment by ili101** [comment]
Thank you
For future reference both problems where solved by installing the package.
