### ISSUE TITLE
Composer installer error

### ISSUE THREAD

**Issue by JonathanSliverLimas** [composer/windows-setup#129]
The Composer installer script was not successful [exit code 1].

OpenSSL failed with a 'certificate verify failed' error. This indicates a problem with the Certificate Authority file(s) on your system, which either cannot be found or may be out of date.

Script Output:
The "https://getcomposer.org/versions" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
Failed to enable crypto
failed to open stream: operation failed

**Comment by johnstevenson** [comment]
Please supply a log file, as requested when you created this issue.
