### ISSUE TITLE
Can't install composer on windows 10

### ISSUE THREAD

**Issue by wijdanMT** [composer/windows-setup#132]
Hi, 
I am encountering a problem in installing it on my pc,
I have read the following similar issue and followed the step's order:

> https://github.com/composer/windows-setup/issues/60

> https://github.com/composer/windows-setup/issues/123

This is my log :
[Setup Log 2021-03-13 #009.txt](https://github.com/composer/windows-setup/files/6134837/Setup.Log.2021-03-13.009.txt)

when I execute "C:\Users\MAHMOU~1\AppData\Local\Temp\is-QSF1R.tmp" on **Run**:
"is-QSF1R.tmp" folder is opened with  stdout.text file contains <C:\Users\MAHMOU~1\AppData\Local\Temp\is-QSF1R.tmp>

I have tried "C:\WINDOWS\system32>sfc /scannow" with no success...

I checked out if the issue is with the user directory name as follows:
![image](https://user-images.githubusercontent.com/80570482/111031612-0f3e8c80-8411-11eb-8a7f-670f91b54e53.png)

**Note** my TMP and TEMP has the same value:
`TEMP=C:\Users\MAHMOU~1\AppData\Local\Temp
TMP=C:\Users\MAHMOU~1\AppData\Local\Temp`

I will appreciate any suggestion to work around this issue

**Comment by johnstevenson** [comment]
Thanks for taking the time to research the problem and provide information based on other issues - that really helps things at this end.

Open your Registry Editor (type "Registry" in the Windows search bar to find it) and look for an `Autorun` entry in the following locations:

- HKEY_CURRENT_USER\SOFTWARE\Microsoft\Command Processor
- HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Command Processor

I suspect that the value will be `1252`.

By default, cmd.exe executes on startup whatever it finds in these two Autorun entries, so you need to delete them.

**Comment by wijdanMT** [comment]
Great! I didn't expect it for a moment that would cause the problem! 
Thanks for your help, I appreciate your time.

**Comment by johnstevenson** [comment]
Glad you got this sorted.

When I replicate this myself (by adding `1252` to  Autorun in the registry), the installer picks up, shows and logs the specific error: 

![autorun](https://user-images.githubusercontent.com/881777/111160989-8baca900-8592-11eb-8448-e5a5a5e156b5.png)

However there is no mention of this in your log file. Could you explain how you solved the issue?
