### ISSUE TITLE
install error: failed+to+open+stream / permission denied

### ISSUE THREAD

**Issue by oryx77** [composer/windows-setup#133]
I've got an error during installing composer. Can you help me please?
![intall_error](https://user-images.githubusercontent.com/84371784/118604038-fa85c880-b7b4-11eb-8b66-89121e892019.png)
Thanks oryx.

**Comment by johnstevenson** [comment]
@oryx77 Could you please supply an error log, as per https://github.com/composer/windows-setup/issues/new

**Comment by johnstevenson** [comment]
Closing, no log supplied.
