### ISSUE TITLE
Cannot install Composer

### ISSUE THREAD

**Issue by jacklythgoee** [composer/windows-setup#138]
Hi all, 
I am unable to install Composer. 

I keep getting exit code 1. 

This is my log
---------------------------
The Composer installer script was not successful [exit code 1].

OpenSSL failed with a 'certificate verify failed' error. This indicates a problem with the Certificate Authority file(s) on your system, which either cannot be found or may be out of date.

Script Output:
The "https://getcomposer.org/versions" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
Failed to enable crypto
Failed to open stream: operation failed

**Comment by johnstevenson** [comment]
No log file supplied.
