### ISSUE TITLE
Error installing composer

### ISSUE THREAD

**Issue by grosvinsanchez** [composer/windows-setup#139]
The Composer installer script was not successful [exit code 1].

Script Output:
The "https://getcomposer.org/versions" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:1408F119:SSL routines:ssl3_get_record:decryption failed or bad record mac
Failed to enable crypto
failed to open stream: operation failed

**Comment by johnstevenson** [comment]
Please supply a log file. Thanks.
