### ISSUE TITLE
The Composer installer script did not run correctly [exit code 259] and no output was returned.

### ISSUE THREAD

**Issue by Iversonweb** [composer/windows-setup#141]
Hey guys i just got a new device so i tried installing composer on it, so i downloaded it from getcomposer.org
and i tried installing but then after clicking next on the ready to install page, ittook me to the page where the installation progress shows but it ended up with the error message below:

"An error occcured. Clicking retry may resolve this issue.
The Composer installer script did not run correctly [exit code 259] and no output was returned."

Please help

**Comment by johnstevenson** [comment]
@Iversonweb Can you please supply a log file, as per the instructions for a new issue: https://github.com/composer/windows-setup/issues/new/

**Comment by rizki1m** [comment]
Hi, 
I also have the same issue, Please help if there is any solution?

**Comment by DoudGaya** [comment]
I'm having the same error. But I think It has to do with the windows not composer

**Comment by johnstevenson** [comment]
We are more than willing to help here, but we can't do anything without a log file. Please create a new issue https://github.com/composer/windows-setup/issues/new/ and follow the instructions.

**Comment by natiyeshi** [comment]
ya please helppppppppppppppppppp
