### ISSUE TITLE
The command interpreter did not run correctly

### ISSUE THREAD

**Issue by Abdalmalekshd** [composer/windows-setup#149]
I'm trying to install composer but I'm getting this Error -> The command interpreter did not run correctly: C:\Windows\system32\cmd.exe and the cmd won't work too

[Setup Log 2023-02-21 #001.txt](https://github.com/composer/windows-setup/files/10793560/Setup.Log.2023-02-21.001.txt)

**Comment by johnstevenson** [comment]
If you supply a log file (as per the instructions shown when you create a new issue), we may be able to see why cmd.exe did not run correctly.

**Comment by Abdalmalekshd** [comment]
> If you supply a log file (as per the instructions shown when you create a new issue), we may be able to see why cmd.exe did not run correctly.

I just uploaded the file sir

**Comment by johnstevenson** [comment]
Thanks for the log. Here is the error message:

```
Error: [ERR_CMD_OUTPUT]
The command interpreter did not run correctly:
C:\Windows\system32\cmd.exe
                          
It did not return the expected output.
```

Basically cmd.exe should have returned the location of the working directory, but did not return any data (you can try it yourself by launching cmd.exe and entering `cd`).

There is something wrong with your Windows installation, because cmd.exe is a core Windows component - and is required by PHP to execute external processes.

**Comment by Abdalmalekshd** [comment]
> Thanks for the log. Here is the error message:
> 
> ```
> Error: [ERR_CMD_OUTPUT]
> The command interpreter did not run correctly:
> C:\Windows\system32\cmd.exe
>                           
> It did not return the expected output.
> ```
> 
> Basically cmd.exe should have returned the location of the working directory, but did not return any data (you can try it yourself by launching cmd.exe and entering `cd`).
> 
> There is something wrong with your Windows installation, because cmd.exe is a core Windows component - and is required by PHP to execute external processes.

Thanks for your reply sir and for your help
