### ISSUE TITLE
When i tried to download laravel version 10 from composer the following given error occur.

### ISSUE THREAD

**Issue by rajcrack** [composer/windows-setup#150]
**Failed to download symfony/process from dist: The zip extension and unzip/7z
 commands are both missing, skipping.**

I have tried to download the laravel globally using the command . the command snippet is given below

**```
C:\Users\Windows** 7>composer global require laravel/installer Changed current directory to C:/Users/Windows 7/AppData/Roaming/Composer
./composer.json has been updated Running composer update laravel/installer
Loading composer repositories with package information Updating dependencies
Nothing to modify in lock file Installing dependencies from lock file (including require-dev)
Package operations: 11 installs, 0 updates, 0 removals
Failed to download symfony/process from dist: The zip extension and unzip/7z commands are both missing, skipping.
The php.ini used by your command-line PHP is: C:\xampp\php\php.ini Now trying to download from source
In GitDownloader.php line 82:
git was not found in your PATH, skipping source download
require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-ins tall] [--no-audit] [--audit-format AUDIT-FORMAT] [--update-no-dev] [-w--update- with-dependencies] [-W--update-with-all-dependencies] [--with-dependencies] [- with-all-dependencies] [-ignore-platform-req IGNORE-PLATFORM-REQ] [-ignore-pla tform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-ol--optimize -autoloader] [-al--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloade r-prefix APCU-AUTOLOADER-PREFIX] [---] [<packages>...]
C:\Users\Windows 7>
```**



What i have to do to stop these error and install the laravel globally . Can you help me in solving this error. I am using xampp control panel 3.3.0./xampp windows*64v 8.2.0. and xampp php version is 8.2.0. composer version is 2.5.5.

i have also tried uncommenting the extension=zip in php.ini but it does not solve my problem. and when i try to run the laravel global install command after uncommenting the extension=zip it willopen a new pop-up window of php interactive shell. What i have to do solve this problem?
my composer temp file is here:-

`

```
> 2023-04-07 13:38:33.635   Log opened. (Time zone: UTC+05:30)
> 2023-04-07 13:38:33.635   Setup version: Inno Setup version 6.2.0
> 2023-04-07 13:38:33.635   Original Setup EXE: C:\Users\Windows 7\Desktop\freefireevent\Composer-Setup (1).exe
> 2023-04-07 13:38:33.635   Setup command line: /SL5="$180306,882897,831488,C:\Users\Windows 7\Desktop\freefireevent\Composer-Setup (1).exe" 
> 2023-04-07 13:38:33.635   Windows version: 6.1.7601 SP1  (NT platform: Yes)
> 2023-04-07 13:38:33.635   64-bit Windows: Yes
> 2023-04-07 13:38:33.635   Processor architecture: x64
> 2023-04-07 13:38:33.635   User privileges: Administrative
> 2023-04-07 13:38:33.635   Administrative install mode: No
> 2023-04-07 13:38:33.635   Install mode root key: HKEY_CURRENT_USER
> 2023-04-07 13:38:33.635   64-bit install mode: No
> 2023-04-07 13:38:33.650   Created temporary directory: C:\Users\WINDOW~1\AppData\Local\Temp\is-URT3N.tmp
> 2023-04-07 13:38:33.666   -- DLL function import --
> 2023-04-07 13:38:33.666   Function name: SetEnvironmentVariableW
> 2023-04-07 13:38:33.666   DLL name: kernel32.dll
> 2023-04-07 13:38:33.666   Dest DLL name: kernel32.dll
> 2023-04-07 13:38:33.666   Importing the DLL function.
> 2023-04-07 13:38:33.666   Successfully imported the DLL function. Delay loaded? Yes
> 2023-04-07 13:38:33.666   -- DLL function import --
> 2023-04-07 13:38:33.666   Function name: ExpandEnvironmentStringsW
> 2023-04-07 13:38:33.666   DLL name: kernel32.dll
> 2023-04-07 13:38:33.666   Dest DLL name: kernel32.dll
> 2023-04-07 13:38:33.666   Importing the DLL function.
> 2023-04-07 13:38:33.666   Successfully imported the DLL function. Delay loaded? Yes
> 2023-04-07 13:38:33.666   -- DLL function import --
> 2023-04-07 13:38:33.666   Function name: SendMessageTimeoutW
> 2023-04-07 13:38:33.666   DLL name: user32.dll
> 2023-04-07 13:38:33.666   Dest DLL name: user32.dll
> 2023-04-07 13:38:33.666   Importing the DLL function.
> 2023-04-07 13:38:33.666   Successfully imported the DLL function. Delay loaded? Yes
> 2023-04-07 13:38:33.666   Extracting temporary file: C:\Users\WINDOW~1\AppData\Local\Temp\is-URT3N.tmp\acls.bat
> 2023-04-07 13:38:33.681   Extracting temporary file: C:\Users\WINDOW~1\AppData\Local\Temp\is-URT3N.tmp\runphp.exe
> 2023-04-07 13:38:33.681   Extracting temporary file: C:\Users\WINDOW~1\AppData\Local\Temp\is-URT3N.tmp\check.php
> 2023-04-07 13:38:33.681   Extracting temporary file: C:\Users\WINDOW~1\AppData\Local\Temp\is-URT3N.tmp\inicheck.php
> 2023-04-07 13:38:33.681   Extracting temporary file: C:\Users\WINDOW~1\AppData\Local\Temp\is-URT3N.tmp\installer.php
> 2023-04-07 13:38:33.697   Extracting temporary file: C:\Users\WINDOW~1\AppData\Local\Temp\is-URT3N.tmp\composer
> 2023-04-07 13:38:33.697   $ Initializing ComposerSetup 6.3.0 for user: Windows 7
> 2023-04-07 13:38:33.697   $ Params: dev=, php=, proxy=, loadinf=
> 2023-04-07 13:38:33.697   $ Getting path info from registry
> 2023-04-07 13:38:33.713   $ Searching for PHP in common locations
> 2023-04-07 13:38:33.713   $ PHP found in 1 location
> 2023-04-07 13:38:33.913   $ WizardPage [001]: Welcome
> 2023-04-07 13:38:33.913   $ WizardPage [100]: Installation Options
> 2023-04-07 13:38:35.205   $ Setup will install 6.3.0 in Standard Mode
> 2023-04-07 13:38:35.205   $ WizardPage [101]: Settings Check
> 2023-04-07 13:38:35.798   $ WizardPage [102]: Running Settings Check
> 2023-04-07 13:38:35.798   $ -- Checking cmd.exe: C:\Windows\system32\cmd.exe --
> 2023-04-07 13:38:35.798   $ -- Execute File --
> 2023-04-07 13:38:35.798   $ Working directory: C:\Users\WINDOW~1\AppData\Local\Temp\is-URT3N.tmp
> 2023-04-07 13:38:35.798   $ Running C:\Windows\system32\cmd.exe /s /c "cd > stdout.txt 2> stderr.txt"
> 2023-04-07 13:38:35.845   $ Success: exit code [0]
> 2023-04-07 13:38:35.860   $ Output from stdout [49 bytes]
>                           C:\Users\WINDOW~1\AppData\Local\Temp\is-URT3N.tmp
> 2023-04-07 13:38:35.860   $ Output from stderr [0 bytes]
> 2023-04-07 13:38:35.860   $ Directory from cmd.exe: C:\Users\WINDOW~1\AppData\Local\Temp\is-URT3N.tmp [C:\Users\WINDOW~1\AppData\Local\Temp\is-URT3N.tmp]
> 2023-04-07 13:38:35.860   $ -- Checking selected php: C:\xampp\php\php.exe --
> 2023-04-07 13:38:35.860   $ Env: PHPRC=, PHP_INI_SCAN_DIR=
> 2023-04-07 13:38:35.860   $ Reading VersionInfo data from exe
> 2023-04-07 13:38:35.860   $ Config: version=8.2.0, id=80200
> 2023-04-07 13:38:35.860   $ -- Checking if php will execute --
> 2023-04-07 13:38:35.860   $ -- Execute File --
> 2023-04-07 13:38:35.860   $ Working directory: C:\Users\WINDOW~1\AppData\Local\Temp\is-URT3N.tmp
> 2023-04-07 13:38:35.860   $ Running C:\Windows\system32\cmd.exe /s /c "runphp.exe C:\xampp\php\php.exe -d error_reporting="E_ALL & ~E_DEPRECATED" -d display_errors=Off -d display_startup_errors=Off -v > stdout.txt 2> stderr.txt"
> 2023-04-07 13:38:36.250   $ Success: exit code [0]
> 2023-04-07 13:38:36.250   $ Output from stdout [153 bytes]
>                           PHP 8.2.0 (cli) (built: Dec  6 2022 15:31:23) (ZTS Visual C++ 2019 x64)
>                           Copyright (c) The PHP Group
>                           Zend Engine v4.2.0, Copyright (c) Zend Technologies
> 2023-04-07 13:38:36.250   $ Output from stderr [0 bytes]
> 2023-04-07 13:38:36.250   $ -- Checking php configuration --
> 2023-04-07 13:38:36.250   $ -- Execute File --
> 2023-04-07 13:38:36.250   $ Working directory: C:\Users\WINDOW~1\AppData\Local\Temp\is-URT3N.tmp
> 2023-04-07 13:38:36.250   $ Running C:\Windows\system32\cmd.exe /s /c "runphp.exe C:\xampp\php\php.exe -d error_reporting="E_ALL & ~E_DEPRECATED" -d display_errors=Off -d display_startup_errors=Off check.php > stdout.txt 2> stderr.txt"
> 2023-04-07 13:38:36.531   $ Success: exit code [0]
> 2023-04-07 13:38:36.531   $ Output from stdout [92 bytes]
>                           <ComposerSetup:>8.2.0|80200|C:\xampp\php\php.ini||C:\xampp\apache\bin\curl-ca-bundle.crt|||1
> 2023-04-07 13:38:36.531   $ Output from stderr [0 bytes]
> 2023-04-07 13:38:36.531   $ Config: version=8.2.0, id=80200, ini=C:\xampp\php\php.ini, other=, cafile=C:\xampp\apache\bin\curl-ca-bundle.crt, capath=, missing=, compat=1
> 2023-04-07 13:38:36.531   $ Ini is compatible: C:\xampp\php\php.ini
> 2023-04-07 13:38:36.531   $ Checking php path
> 2023-04-07 13:38:36.531   $ Checking composer bin path
> 2023-04-07 13:38:36.531   $ Registering: Add to User path: C:\Users\Windows 7\AppData\Local\ComposerSetup\bin
> 2023-04-07 13:38:36.531   $ Checking PathExt values for .BAT
> 2023-04-07 13:38:36.531   $ Registering: Add to User path: C:\Users\Windows 7\AppData\Roaming\Composer\vendor\bin
> 2023-04-07 13:38:36.547   $ WizardPage [101]: Settings Check
> 2023-04-07 13:38:36.547   $ No proxy found
> 2023-04-07 13:38:36.547   $ WizardPage [104]: Proxy Settings
> 2023-04-07 13:38:37.561   $ UpdateReadyMemo
>                           PHP version 8.2.0
>                                 C:\xampp\php\php.exe
>                           
>                           Proxy: none
> 2023-04-07 13:38:37.576   $ WizardPage [010]: Ready to Install
> 2023-04-07 13:38:38.044   $ WizardPage [105]: Running Composer Install
> 2023-04-07 13:38:38.044   $ Running Composer installer script
> 2023-04-07 13:38:38.044   $ -- Execute File --
> 2023-04-07 13:38:38.044   $ Working directory: C:\Users\WINDOW~1\AppData\Local\Temp\is-URT3N.tmp
> 2023-04-07 13:38:38.044   $ Running C:\Windows\system32\cmd.exe /s /c "C:\xampp\php\php.exe -d error_reporting="E_ALL & ~E_DEPRECATED" -d display_errors=Off -d display_startup_errors=Off installer.php -- --no-ansi --quiet > stdout.txt 2> stderr.txt"
> 2023-04-07 13:39:49.764   $ Success: exit code [0]
> 2023-04-07 13:39:49.764   $ Output from stdout [0 bytes]
> 2023-04-07 13:39:49.764   $ Output from stderr [0 bytes]
> 2023-04-07 13:39:49.764   $ WizardPage [010]: Ready to Install
> 2023-04-07 13:39:49.764   $ WizardPage [011]: Preparing to Install
> 2023-04-07 13:39:49.764   $ Running PrepareToInstall tasks
> 2023-04-07 13:39:49.764   $ Writing Unix line-endings to C:\Users\WINDOW~1\AppData\Local\Temp\is-URT3N.tmp\composer
> 2023-04-07 13:39:49.764   $ Making changes to the environment: 2 changes registered
> 2023-04-07 13:39:49.764   $ Adding 'C:\Users\Windows 7\AppData\Local\ComposerSetup\bin' to [HKCU\Environment\PATH]
> 2023-04-07 13:39:49.764   $ Adding 'C:\Users\Windows 7\AppData\Roaming\Composer\vendor\bin' to [HKCU\Environment\PATH]
> 2023-04-07 13:39:49.779   $ WizardPage [012]: Installing
> 2023-04-07 13:39:49.826   Starting the installation process.
> 2023-04-07 13:39:49.826   Creating directory: C:\Users\Windows 7\AppData\Local\ComposerSetup
> 2023-04-07 13:39:49.826   Directory for uninstall files: C:\Users\Windows 7\AppData\Local\ComposerSetup
> 2023-04-07 13:39:49.826   Creating new uninstall log: C:\Users\Windows 7\AppData\Local\ComposerSetup\unins000.dat
> 2023-04-07 13:39:49.826   -- File entry --
> 2023-04-07 13:39:49.826   Dest filename: C:\Users\Windows 7\AppData\Local\ComposerSetup\unins000.exe
> 2023-04-07 13:39:49.842   Time stamp of our file: 2023-04-07 13:38:31.320
> 2023-04-07 13:39:49.842   Installing the file.
> 2023-04-07 13:39:49.857   Successfully installed the file.
> 2023-04-07 13:39:49.857   -- File entry --
> 2023-04-07 13:39:49.857   Dest filename: C:\Users\Windows 7\AppData\Local\ComposerSetup\bin\composer.bat
> 2023-04-07 13:39:49.857   Time stamp of our file: 2020-12-11 16:18:28.000
> 2023-04-07 13:39:49.857   Installing the file.
> 2023-04-07 13:39:49.857   Creating directory: C:\Users\Windows 7\AppData\Local\ComposerSetup\bin
> 2023-04-07 13:39:49.857   Successfully installed the file.
> 2023-04-07 13:39:49.857   -- File entry --
> 2023-04-07 13:39:49.857   Dest filename: C:\Users\Windows 7\AppData\Local\ComposerSetup\bin\composer
> 2023-04-07 13:39:49.857   Time stamp of our file: 2023-04-07 13:39:49.764
> 2023-04-07 13:39:49.857   Installing the file.
> 2023-04-07 13:39:49.857   Successfully installed the file.
> 2023-04-07 13:39:49.857   -- File entry --
> 2023-04-07 13:39:49.857   Dest filename: C:\Users\Windows 7\AppData\Local\ComposerSetup\bin\composer.phar
> 2023-04-07 13:39:49.857   Time stamp of our file: 2023-04-07 13:39:49.717
> 2023-04-07 13:39:49.857   Installing the file.
> 2023-04-07 13:39:49.857   Successfully installed the file.
> 2023-04-07 13:39:49.857   Saving uninstall information.
> 2023-04-07 13:39:49.857   Writing uninstaller messages: C:\Users\Windows 7\AppData\Local\ComposerSetup\unins000.msg
> 2023-04-07 13:39:49.857   Creating new uninstall key: HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\{7315AF68-E777-496A-A6A2-4763A98ED35A}_is1
> 2023-04-07 13:39:49.857   Writing uninstall key values.
> 2023-04-07 13:39:49.857   Detected previous administrative 32-bit install? No
> 2023-04-07 13:39:49.857   Detected previous administrative 64-bit install? No
> 2023-04-07 13:39:49.951   Installation process succeeded.
> 2023-04-07 13:39:49.951   Need to restart Windows? No
> 2023-04-07 13:39:49.966   $ WizardPage [107]: Information
> 2023-04-07 13:40:05.496   $ WizardPage [014]: Setup Completed
> 2023-04-07 13:40:07.680   Deinitializing Setup.
> 2023-04-07 13:40:07.696   Log closed.
> `
```

**Comment by Zack4DEV** [comment]
@rajcrack  try to modify your composer.json ,in "Preferred-install": "dist" , 'dist' value by 'source'
