### ISSUE TITLE
cURL requests in Composer installer fail to check cert revocation when installing through TIC Gateway

### ISSUE THREAD

**Issue by jesseVA** [composer/windows-setup#151]
When trying to install Composer through our organization's [TIC Gateway](https://www.gsa.gov/technology/technology-products-services/it-security/trusted-internet-connections-tic) I receive the following error in the installer:

> The Composer installer script was not successful [exit code 1].
> 
> OpenSSL failed with a 'certificate verify failed' error. This indicates a problem with the Certificate Authority file(s) on your system, which either cannot be found or may be out of date.
> 
> Script Output:
> The "https://getcomposer.org/versions" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
> error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
> Failed to enable crypto
> Failed to open stream: operation failed

The server is configured with the most current CA certificates from the cURL site https://curl.se/docs/caextract.html

Any assistance on this issue would be greatly appreciated. :)

[Setup Log 2023-05-01 #006.txt](https://github.com/composer/windows-setup/files/11368251/Setup.Log.2023-05-01.006.txt)

**Comment by johnstevenson** [comment]
The installer script doesn't actually use curl and provides its own root certificate for `getcomposer.org` anyway.

The only time this certificate is not used (on Windows) is if a certificate location is found from an environment or ini setting:

- env: `SSL_CERT_FILE`
- env: `SSL_CERT_DIR`
- ini: `openssl.cafile`
- ini: `openssl.capath`

In your case, these ini values are not set. I don't know how your gateway works, but I would imagine it acts as a proxy server, in which case you need to set an `http_proxy` environment variable.
