### ISSUE TITLE
Shim script wrongly assumes all "Windows paths" in Cygwin start with `/proc/cygdrive`

### ISSUE THREAD

**Issue by HoldYourWaffle** [composer/windows-setup#153]
The "using Windows php" check of the [composer shim script](https://github.com/composer/windows-setup/blob/d91b8bc578240442e7a3c5b31211d4ea1711cb33/src/shims/composer) fails if `fstab` is used to mount a Windows path outside of `/proc/cygdrive`.
In my case `which php` outputs `/c/tools/php82/php`, while `readlink -n /proc/cygdrive` outputs `/cygdrive`, resulting in the following error:
```
Could not open input file: /c/ProgramData/ComposerSetup/bin/composer.phar
```
In other words: the script wrongly assumes all "Windows paths" start with `/proc/cygdrive`.

This check was introduced in ae29413, but as far as I can tell "Cygwin PHP" understands Windows-style paths just fine, so the extra "Windows PHP"-check could be removed.

**Comment by johnstevenson** [comment]
>  the script wrongly assumes all "Windows paths" start with /cygdrive

This is not the case. Please see: https://github.com/composer/windows-setup/pull/78

**Comment by HoldYourWaffle** [comment]
Woops that's poor phrasing on my end.

#78 / 907ca7b solves a different problem. `/proc/cygdrive` will point to whatever `/cygdrive` is aliased to, but with `fstab` Windows paths can be mounted to _any_ path in the POSIX filesystem. See [Using Cygwin - The Cygwin Mount Table](https://cygwin.com/cygwin-ug-net/using.html#mount-table).

On my system `/proc/cygdrive` is still `/cygdrive`, but my `C:/` is also mounted to `/c`. Therefore my Windows paths start with `/c`, not with the value of `/proc/cygdrive`.
