### ISSUE TITLE
I tried new and this is its new file created, thnx for reply

### ISSUE THREAD

**Issue by MrEveryThingSafdar** [composer/windows-setup#156]
[Setup Log 2023-12-13 #001.txt](https://github.com/composer/windows-setup/files/13664016/Setup.Log.2023-12-13.001.txt)

**Comment by johnstevenson** [comment]
You have an `http_proxy` environment variable set, which could be causing the problem if it is incorrect.

**Comment by MrEveryThingSafdar** [comment]
I tried to set off proxy settings in my windows, I followed :
start/settings/network&internet/proxy and this is its image:
![proxy](https://github.com/composer/windows-setup/assets/106355034/794fdbd1-424b-4f1e-ba4e-594c4111d65c)

how do I have to change that, or I have to fix that from some where else?

**Comment by johnstevenson** [comment]
Search Windows Settings for "environment variables". An `http_proxy` variable will be in either the User or System list.

**Comment by MrEveryThingSafdar** [comment]
I deleted it, and then successfully installed composer, very very very
thanx sir. but I have  a question, does not have to be there that
http_proxy? and if not have to be , why there was?!

**Comment by johnstevenson** [comment]
I'm glad you fixed it.

Unless you remember setting the `http_proxy` environment variable yourself (via Windows settings), then I suspect that another installer program has added it for you.
