### ISSUE TITLE
composer

### ISSUE THREAD

**Issue by MARGARIDA76** [composer/windows-setup#161]

**Comment by MARGARIDA76** [comment]
The Composer installer script did not run correctly [exit code 1].

Script Output:
PHP Warning:  Module "openssl" is already loaded in Unknown on line 0

**Comment by johnstevenson** [comment]
You need to fix your `php.ini` file so that the openssl extension is only loaded once.

**Comment by MARGARIDA76** [comment]
How can I do it, I have tried but no solution can you explain me well step by step please.

Enviado do Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by johnstevenson** [comment]
Open the file, search for `extension=openssl`, remove the duplicate entry.

**Comment by MARGARIDA76** [comment]
I have tried that but the problem is continuing

Enviado do Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by johnstevenson** [comment]
I cannot really help you without a log file (as requested when you opened this issue).

**Comment by MARGARIDA76** [comment]
Thank you very much for spend your time to guide me for resolution

Enviado do Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
