### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by alexkirana** [composer/windows-setup#162]
The PHP exe file you specified did not run correctly:
C:\xampp\php\php.exe

The php.ini used by your command-line PHP is: C:\xampp\php\php.ini

A duplicate setting in your php.ini could be causing the problem.

Program Output:
PHP Warning:  Module "curl" is already loaded

**Comment by johnstevenson** [comment]
Look in your php.ini file for the following lines:

```
extension=curl
```

And make sure that there is only one entry.
