### ISSUE TITLE
solve kar do

### ISSUE THREAD

**Issue by dhruvprabatni** [composer/windows-setup#163]
The Composer installer script was not successful [exit code 1].

OpenSSL failed with a 'certificate verify failed' error. This indicates a problem with the Certificate Authority file(s) on your system, which may be out of date.

Certificate location [from openssl.cafile ini setting]:
C:\xampp\php\cacert.pem

The php.ini used by your command-line PHP is: C:\xampp\php\php.ini

Script Output:
The "https://getcomposer.org/versions" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:0A000086:SSL routines::certificate verify failed
Failed to enable crypto
Failed to open stream: operation failed

**Comment by johnstevenson** [comment]
You need to update your certificate bundle at `C:\xampp\php\cacert.pem`

Or you can just comment out the `openssl.cafile` setting in your ini file, which allows the default certificate bundle to be used.
