### ISSUE TITLE
Composer environment problem

### ISSUE THREAD

**Issue by IndraWilmansyah** [composer/windows-setup#164]
i'm new on laravel and php stuff,but when i want to check and update my composer it always gave me this warning :

 **" The COMPOSER environment variable is set to C:\ProgramData\ComposerSetup\bin which is a directory, this variable should point to a composer.json or be left unset."**
  
What should i do,i'm in the middle of working on my laravel project,could anyone help me solve this problems?

**Comment by johnstevenson** [comment]
You need to remove the `COMPOSER` environment variable, which is not generally needed.

**Comment by IndraWilmansyah** [comment]
@johnstevenson could you show me how to remove it,since i'm new with this kind of stuff?

**Comment by johnstevenson** [comment]
Go to Control Panel, System, Advanced, Environment Variables.

If you need more help, just Google it.

**Comment by Nephas10** [comment]
@johnstevenson So All i need is just to install composer and remove the system variable right?
