### ISSUE TITLE
how to tell composer which php.ini file should be used for current project?

### ISSUE THREAD

**Issue by mech01nc01** [composer/windows-setup#166]
Hello, just as the title says, how to tell composer which php.ini-file to use?

**Comment by johnstevenson** [comment]
PHP loads the ini file(s) from known locations: See https://www.php.net/manual/en/configuration.file.php

To use a different ini file, you can pass its location on the PHP command line, using the `-c` option:

```sh
path/to/php.exe -c path/to/ini path/to/composer.phar
```

**Comment by mech01nc01** [comment]
yes i'm aware how php loads its config
ok so composer is just a php-"script" if i understand that correctly, so typing composer in cmd will just do 
```
php path/to/composer.phar
```

do you know where i can edit this command to add my ini-file?

**Comment by johnstevenson** [comment]
You can edit the shim scripts in the bin directory:

https://github.com/composer/windows-setup#Install-Locations

**Comment by mech01nc01** [comment]
ah nice thanks, that was the relevant information ;) works now without warnings
