### ISSUE TITLE
The Composer installer script was not successful [exit code 1].  Script Output: Failed to decode zlib stream

### ISSUE THREAD

**Issue by FahadQasim283** [composer/windows-setup#167]

**Comment by johnstevenson** [comment]
Please supply a log file, as requested in the issue template.

**Comment by FahadQasim283** [comment]
which log file? this issue is generated while installing composer in my windows 11, can you guide me how to solve this

**Comment by Maryammalik21** [comment]
facing same issue :)

**Comment by johnstevenson** [comment]
@Maryammalik21 Please create a new issue and supply a log file, as requested in the issue template.
