### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by QuietCodeJourney** [composer/windows-setup#169]
The Composer installer script was not successful [exit code 1].

OpenSSL failed with a 'certificate verify failed' error. This indicates a problem with the Certificate Authority file(s) on your system, which either cannot be found or may be out of date.

Script Output:
The "https://getcomposer.org/versions" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:0A000086:SSL routines::certificate verify failed
Failed to enable crypto
Failed to open stream: operation failed

**Comment by Hellpsuport** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Composer Support Request](https://generalwebfixes.web.app/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by johnstevenson** [comment]
Please supply a log file, as per the instructions you see when opening a new issue.

**Comment by Hellpsuport** [comment]
Go to the support link I gave you to resolve your issue immediately

**Comment by QuietCodeJourney** [comment]
thank you. but its already solve..

**Comment by klorinczi** [comment]
I had "error:0A000086:SSL routines::certificate verify failed" error on Windows when installing Composer-Setup.exe.

After temporarily disabling the Avast/AVG antivirus, the "composer" installed successfully.

Solution source:
https://stackoverflow.com/a/79463726/4523359
