### ISSUE TITLE
Add Explorer context menus

### ISSUE THREAD

**Issue by cmenning** [composer/windows-setup#27]
It would be nice to have an Explorer context menu to enable running "install" or "update" without dropping into the command line.

**Comment by vahidalvandi** [comment]
in windows you can press SHIFT and right click to any folder show more option like open command window here

[](http://webineh.net)

**Comment by ahmednawzbutt** [comment]
@vahidalvandi Thanx a lot man!
solved my Problem

Qouting your solution.
"
in windows you can press SHIFT and right click to any folder show more option like open command window here
"

**Comment by CagatayUlubay** [comment]
Before this is closed again, why are the context menu items removed (4.1)? Let the one who want to use the cmd line use it and them who want to use the context menu use the context menu.

I have like 10 open applications and I am happy to have a window less. It's much faster to press Rightclick->Composer Update rather then use two hands to Shift+Rightclick and write the "composer update". After the context menu process, I close the window and done.

Even with a opened cmd line it's usually not in the correct folder, so first I have to move to the correct dir, before I can update composer.. this is everything time consuming. It's cool to know how to use the cmd, but not necessary. It's nothing that needs support too.. it's a harmless, already existing function to add context menu that was removed.. for what? To be cool again with only using the black window and everyone thinking you're a mage? I don't know.. I am using the Shift+Rightclick to open a cmd line and write it out now, but that is so unnecessary.. :-1:
