### ISSUE TITLE
Inexplicable Error: (XAMPP) Composer Error [ERR_DOWNLOAD]: Composer was not downloaded

### ISSUE THREAD

**Issue by dtruel** [composer/windows-setup#32]
I just downloaded and tried to install, and this is the only message I got.  I can't what the issue is because I don't really know what the problem is.  If there could be more specificity in the error message as to what the real problem is, that would help solve the issue.  I wish I didn't have to request a fix here, but this isn't quite my area of expertise. Running windows 8.1

**Comment by johnstevenson** [comment]
This has been fixed in [v4.1.0](https://github.com/composer/windows-setup/releases/tag/v4.1.0), which recognizes common PHP config errors and displays all output.
