### ISSUE TITLE
Installer fails with ERR_INVALID

### ISSUE THREAD

**Issue by johnstevenson** [composer/windows-setup#36]
See https://github.com/composer/composer/issues/3324

The issue concerns the first time the installer calls the setup.php script, via cmd.exe (or whatever ```%ComSpec%``` points to) and outputting the result to result.txt in the installer temp dir.

- php returned a failure exit code of 1.
- setup.exe saw that the first line of ```result.txt``` was not as expected and showed a general error.

Todo in next release:
- dump ```result.txt``` content in the log, for debugging
- show the content to the user
- change the ERR_INVALID explanation text to be more specific

**Comment by curry684** [comment]
Yikes, just spent an hour debugging to find this precise explanation of my findings. It's become more problematic now as Composer can no longer work without OpenSSL, and as such the missing check for that causes more people to run into this.

See https://github.com/composer/composer/issues/3324#issuecomment-183097075 for my specific findings in this regard.

**Comment by johnstevenson** [comment]
This has been fixed in [v4.1.0](https://github.com/composer/windows-setup/releases/tag/v4.1.0), which recognizes common PHP config errors and displays all output. The user now has the option to manually enabled open_ssl, or continue without it.
