### ISSUE TITLE
Add vendor/bin to the Path

### ISSUE THREAD

**Issue by pjcdawkins** [composer/windows-setup#37]
As far as I can see, Composer-Setup adds `composer` to the Path, but it doesn't yet add globally installed binaries (i.e. it doesn't add the `vendor/bin` directory).

This is something users find difficult so it would be a really useful feature in the installer.

**Comment by dbwhddn10** [comment]
i have same problem.

in my case.

add c:\ProgramData\ComposerSetup\bin to Window PATH Variable when composer-setup.exe installed..

but when execute 
```
composer global require "phpunit/phpunit=4.4.*"
```
phpunit installed in %APPDATA%\Composer\bin

**Comment by dbwhddn10** [comment]
i ran cmd.exe and test with admin and user authority

**Comment by johnstevenson** [comment]
This has been fixed in [v4.1.0](https://github.com/composer/windows-setup/releases/tag/v4.1.0). Thanks for reporting it.

**Comment by oliverlukedavenport** [comment]
I'm having this issue with v4.7.0

%APPDATA%\Composer\vendor\bin was added to PATH, but the "vendor" directory doesn't exist.

**Comment by johnstevenson** [comment]
The installer doesn't create the directory, if this is what you mean? If not, could you please open a new issue and include the log file - thanks.

**Comment by elkarouani** [comment]
Hi guys, i have a problem when installing composer, the folders {vendor & bin} doesn't been created !
And when i create a project with composer, or updating it, i get this result 
=====> 
Loading composer repositories with package information
Updating dependencies (including require-dev)

  [ErrorException]
  file_put_contents(C:/Users/KDragon/AppData/Local/Composer/repo/https---repo.packagist.org/provider-laravel$laravel.json): failed to open stream: Invalid argument

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...
