### ISSUE TITLE
Composer could not find The config file...

### ISSUE THREAD

**Issue by Bouhoum** [composer/windows-setup#40]
I'm new to laravel & composer, I used composer to download a package for L5, when I made changes on the json file, i did a composer update & got this following issue

```
D:\wamp\www\laravel>composer update
Composer could not find the config file: C:\ProgramData\ComposerSetup\bin
To initialize a project, please create a composer.json file as described in the http://getcomposer.org/ "Getting Started" section
```

Please any idea on how to solve this ?

**Comment by johnstevenson** [comment]
This error message implies that you are calling composer from its default install directory (```C:\ProgramData\ComposerSetup\bin```), although you report that you called it from the project directory (```D:\wamp\www\laravel>composer update```).

Any ideas @Seldaek before I download wamp and laravel and try to reproduce?

**Comment by Bouhoum** [comment]
Well I uninstalled composer & deleted all Laravel files & re-installed composer & laravel using it, after finishing the download I got this following error message again
```
Created project in D:\wamp\www\laravel



  [InvalidArgumentException]
  Composer could not find the config file: C:\ProgramData\ComposerSetup\bin
  To initialize a project, please create a composer.json file as described in the http://getcomposer.org/ "Getting Sta



create-project [-s|--stability="..."] [--prefer-source] [--prefer-dist] [--repository-url="..."] [--dev] [--no-dev] [-
no-scripts] [--no-progress] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [package] [directory] [version]

```
& if this may help I have two composer folders, one in AppData/local & another in AppData/roaming.
the local one has some folders (2) & .htaccess
the Roaming one has only 2 files, .hataccess & cacert.pem

Thank u

**Comment by Seldaek** [comment]
AFAIK `Composer could not find the config file: C:\ProgramData\ComposerSetup\bin` means that you have a COMPOSER environment variable defined and set to `C:\ProgramData\ComposerSetup\bin`. You should unset/delete that env var.

**Comment by Bouhoum** [comment]
Thank u, u saved my life .-.

**Comment by frankmaina** [comment]
+1 on this one

**Comment by cmosguy** [comment]
+1 this saved me today! thanks! @Seldaek

**Comment by AfuBasic** [comment]
Mehn, I would have kissed you if you were around, being on these shit for close to 24 hours, you just eased my tension. Thumbs up buddy

**Comment by JasaPC** [comment]
+1 thanks a lot! :D

**Comment by pparmentier** [comment]
Thanks, helped me too !

**Comment by johnstevenson** [comment]
@pparmentier Any ideas how the `COMPOSER` environment variable came to be set in the first place?

**Comment by pparmentier** [comment]
@johnstevenson I set it myself while trying to make a TFS build on a Windows agent leveraging composer functional and forgot about it after that...

**Comment by johnstevenson** [comment]
@pparmentier Thanks. I was just wondering whether to check for it in Composer-Setup, as it seems to be an occasional problem.

Can I ask why you set it? And why you set it to a directory, rather than the filepath to an alternatively named `composer.json`? I guess there must be some incorrect instructions out there somewhere.

**Comment by pparmentier** [comment]
Everything was just my fault, really. 
I was trying to make composer on a non interactive TFS agent and tried all I can before realizing I was editing variables on the wrong user account. :)

**Comment by johnstevenson** [comment]
@pparmentier Ok, thanks.

**Comment by Pistone45** [comment]
> AFAIK `Composer could not find the config file: C:\ProgramData\ComposerSetup\bin` means that you have a COMPOSER environment variable defined and set to `C:\ProgramData\ComposerSetup\bin`. You should unset/delete that env var.

Thank you man

**Comment by codenex1** [comment]
thanks bro +1
