### ISSUE TITLE
Composer installation issues on windows 7 with wampserver2.5

### ISSUE THREAD

**Issue by sombir** [composer/windows-setup#43]
I am also facing some problem installing composer on window 7 any one found the solution of this problem please help.

i am getting below error : 

Connection error [ERR_CONNECTION]:Unable to connect to getcomposer.org

Request to http://getcomposer.org/installer failed with errors:
Failed to open stream: A connection attempt failed because the connected party 
did not properly respond after a period of time, or established connection failed 
because connection host has failed to respond.

extension php_openssl and 'php_curl` already enabled in php.ini file lacated in C:\wamp\bin\php\php5.5.12.

When i run the ping command ping composer.org it is giving me below error :

Pinging 69.172.201.208 with 32 bytes of data
Reply from 10.206.30.1: Destination host unreachable
Reply from 10.206.30.1: Destination host unreachable
Reply from 10.206.30.1: Destination host unreachable
Reply from 10.206.30.1: Destination host unreachable

Please help to solve this issue.

**Comment by johnstevenson** [comment]
Try pinging getcomposer.org rather than composer.org. The response should look like:

```
Pinging getcomposer.org [87.98.253.108] with 32 bytes of data:
Reply from 87.98.253.108: bytes=32 time=18ms TTL=55
Reply from 87.98.253.108: bytes=32 time=18ms TTL=55
Reply from 87.98.253.108: bytes=32 time=19ms TTL=55
Reply from 87.98.253.108: bytes=32 time=21ms TTL=55
```
However, the fact that your ping replies from a private IP address ```10.206.30.1``` suggests that there may be a proxy or something getting in the way.

**Comment by sombir** [comment]
Thanks for giving your valuable time.

![untitled](https://cloud.githubusercontent.com/assets/5450867/8497703/f18d9226-219c-11e5-85d4-a26034c2fb43.png)

same error in both cases ping composer.org and ping getcomposer.org see the attached screen shot.

How i can resolve the proxy issue?.

Thanks.
Thanks for giving your valuable time

**Comment by johnstevenson** [comment]
So, presuming you have a proxy (and the installer has been unable to find its settings in your registry) you need to add a user environment variable named named HTTP_PROXY with the value ```http://proxyurl.com``` or if it requires a username and password then ```http://username:password@proxyurl.com``` (note that in the latter case the password is now stored in plaintext in the registry)

**Comment by johnstevenson** [comment]
Proxy handling has been improved in [v4.1.0](https://github.com/composer/windows-setup/releases/tag/v4.1.0), with a new page to enter your settings (if they haven't been detected) and create the `http_proxy` variable for you.
