### ISSUE TITLE
Installation fails behind proxy

### ISSUE THREAD

**Issue by avindra** [composer/windows-setup#44]
Message:

```
Connection Error [ERR_CONNECTION]: Unable to connect to getcomposer.org

Request to http://getcomposer.org/installer failed with errors:
Failed to open stream: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```

I'm pretty sure this is due to proxy settings. Is there a way to get the installer to pick up the proxy settings already configured on my system?

**Comment by alcohol** [comment]
Not as far as I can see in [getcomposer.org/installer](/composer/getcomposer.org/blob/master/web/installer).

**Comment by alcohol** [comment]
Oh wait, did you actually use the Windows installer (.exe) ?

**Comment by avindra** [comment]
Yes, that's the message coming from the .exe

**Comment by avindra** [comment]
I actually just develop from Linux (on the server), and was recently looking in to working from Windows (i.e., using PHP's built in server, etc). 

I'm actually using Bash (the one bundled with cmder). It looks like downloading the .phar, symlinking the phar to /bin/composer and calling "composer" does the trick... no need for the Windows installer with that route.

**Comment by alcohol** [comment]
Not sure what the options are with the Windows installer.

/cc @johnstevenson might know.

**Comment by johnstevenson** [comment]
The Windows installer looks for proxy information in the following places:

* environment variables (```http_proxy```, ```https_proxy```, case insensitive)

* registry key ```HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings``` for ```ProxyEnable```, ```ProxyOverride``` or ```ProxyServer``` values.

@avindra Where are your settings stored?

**Comment by avindra** [comment]
I had both http_proxy and https_proxy set in the environment.

**Comment by johnstevenson** [comment]
Interesting, because the error message should have shown the proxy url. If you run the installer from the command line: 

    Composer-Setup.exe /LOG="full path\to\log.txt"

you may get more of an explanation in the log file.

**Comment by johnstevenson** [comment]
In [v4.1.0](https://github.com/composer/windows-setup/releases/tag/v4.1.0), the installer will show you any proxy settings it has found, and let you change/add your own. Not sure if this would have helped here, but who knows.
