### ISSUE TITLE
The PHP exe file you specified did not execute correctly: 

### ISSUE THREAD

**Issue by laxman1223** [composer/windows-setup#47]
![capture](https://cloud.githubusercontent.com/assets/1289975/13211657/43d1691a-d960-11e5-88f7-20e0839e3cf3.JPG)

**Comment by johnstevenson** [comment]
Try running ```C:\xampp\php\php.exe -v``` from the command line.

**Comment by laxman1223** [comment]
![c1](https://cloud.githubusercontent.com/assets/1289975/13217019/a022d26a-d985-11e5-9673-e342cf3d65d7.JPG)

**Comment by alcohol** [comment]
You need to fix that warning.

**Comment by laxman1223** [comment]
fixed
