### ISSUE TITLE
Add a new setting to download the dev version

### ISSUE THREAD

**Issue by paladox** [composer/windows-setup#48]
Hi please add support for a new setting that will download the dev version instead of the stable one if the user wanted too.

**Comment by alcohol** [comment]
Unless I am mistaken, it does use the getcomposer.org/installer, which by default installs the latest dev version (no stable version exists at the moment, only tagged alpha's).

**Comment by paladox** [comment]
Yes but I mean download straight of the master branch please.

**Comment by alcohol** [comment]
The getcomposer.org/installer downloads the latest snapshot (which can also be found on https://getcomposer.org/download/). This equals the latest commit of master.

**Comment by johnstevenson** [comment]
Yup, it uses the getcomposer.org/installer, which downloads whatever is considered *the* version. It has a flag for downloading a different *version*, but we don't use that (and I am not sure that it would be applicable to an easy-use, generic setup program)
