### ISSUE TITLE
Windows installer does not see Denwer's virtual drive

### ISSUE THREAD

**Issue by Marat-Tanalin** [composer/windows-setup#49]
Cannot install Composer using its Windows installer: it requests for php.exe location, but just does not see the virtual drive created by [Denwer](http://www.denwer.ru/) (WAMP-type web-server popular in Russia).

FWIW, Denwer uses Windows' built-in `subst.exe` utility to create virtual drives.

**Comment by johnstevenson** [comment]
True, but only because the File Browser control does not show the substituted drive. It works if a drive is "Shared" as a network drive.

**Comment by Marat-Tanalin** [comment]
FWIW, other applications that have the absolutely similar file browser see the virtual drive without problems, and Composer’s installer is the only application I’ve ever seen that has this issue.

Could File Browser control used in Composer’s installer be fixed not to exclude virtual drives? (I suspect this is a matter of something like a single line or a single function argument in code.) Thanks.

**Comment by johnstevenson** [comment]
Sorry, but there is absolutely no point in changing anything, because a virtual drive-mapping in the environment path cannot be resolved. In fact I think this is the case for any drive mapping. As I said above, UNC shares work (if you really need to map to somewhere).

The solution is to browse to, and select the physical path - simple!

Note that you can't bypass the File Browser and I am not sure how you pasted anything into the text box because it is meant to be read-only.

**Comment by Marat-Tanalin** [comment]
> virtual drive-mapping in the environment path cannot be resolved.

If this is impossible technically, OK.

> The solution is to browse to, and select the physical path - simple!

Selecting physical path results in the following error:

    The PHP exe file you specified did not execute correctly
    Internal Error [ERR_INVALID], exit code 0

> you can't bypass the File Browser and I am not sure how you pasted anything into the text box because it is meant to be read-only.

The text field to the left of the “Browse button” is in fact not read-only: I can paste or type-in anything into it (Windows 7 Home Premium 64bit).

**Comment by johnstevenson** [comment]
Run ```...\php.exe -v``` from the command line. It should give you a clue what is wrong.

**Comment by Marat-Tanalin** [comment]
As expected, php cannot find extension DLLs which paths are specified in php.ini using the (nonexistent when running from physical location) virtual drive as root. Never mind, though. If the bug is not fixable, I’m closing the bug. Thanks for your attention.

**Comment by johnstevenson** [comment]
Shame it didn't work out for you. I wouldn't call it a bug at our end - it's a pretty strange setup using a virtual drive anyway. Also, looking at the link you posted, the distribution seems to be installing php 5.3.13, which is very old, buggy and insecure. You should really be using a more modern version if you can.

**Comment by Marat-Tanalin** [comment]
Of course, I regularly update its components (e.g. Apache and PHP) to the latest available versions. :-)
