### ISSUE TITLE
New version feedback

### ISSUE THREAD

**Issue by johnstevenson** [composer/windows-setup#51]
[ComposerSetup.4.0.1.exe - beta](https://s3-eu-west-1.amazonaws.com/johnstevenson/composer/Composer-Setup.4.0.1.exe)

I could do with some feedback on the new version, which is almost done. You will have to uninstall any previous versions, because I've retired the shell-menus feature. The main changes are:

- Finds common php locations (xampp, wamp etc) and presents them to the user.
- Simpler error handling which displays all php output received.
- A new Security page, shown when openssl is not available, with an optional ```DisableTls``` flag (with suitable warnings).
- A new Proxy page, allowing the user to input an ```http_proxy``` value. Details are taken from the registry if available. The variable is then set in the User environment (but not deleted on Uninstall). The page is not shown if http_proxy is already set.
- ```Composer\vendor\bin``` added to the User path (other users will have to add this manually).
- Initial version of silent installs and uninstalls with the /SILENT param
- Dual code signing (SHA1, SHA2) of the exes and dll, to satisfy new Windows requirements.

The one thing left to implement is removing the Compose home stuff on uninstall (currently it only offers to remove the cache/config data).

It would be helpful if it could be tested with as broken a system as possible - allow_url_open set to off, phar disabled, openssl extension disabled, no php ini, repeated dll extension lines in the ini, etc.
You can make modifications to stuff when the installer is running - just go back to the Settings page and start again (environment changes are also picked up). You can do simple proxy tests by installing Fiddler4.

Thanks to anyone who is prepared to help.
@Seldaek Is this worth linking to as a Composer issue, for wider coverage?

**Comment by Seldaek** [comment]
I created an issue, hopefully people are looking ;)

**Comment by johnstevenson** [comment]
Latest: [Composer-Setup.4.0.2.exe beta](https://s3-eu-west-1.amazonaws.com/johnstevenson/composer/Composer-Setup.4.0.2.exe)

Main changes are a better implementation of unattended installs (hopefully), allowing command line params together with `/LOADINF` and `/SAVEINF` functionality:

Params are:

- `/PHP="path\to\php.exe"`
- `/PROXY="httpproxy"`
- `/SILENT` as per Inno documentation
- `/VERYSILENT` as per Inno documentation
- `/LOADINF` as per Inno documentation
- `/SAVEINF` as per Inno documentation
    
The Proxy page is always shown now and is informational when either a /PROXY param (or a LoadInf value) is present, or there is an http(s)_proxy value in the environment.

@curry864 Was your expression of undying love for me because you were just please I'd got round to doing this, or was it because you had actually tested it and everything was okay! If the latter, then I would appreciate you checking that I haven't broken anything - thanks.

**Comment by curry684** [comment]
Sorry that was my undying love for you and doing the work on the new version of the installer hehe. Kinda stoked on time right now to do real testing.

**Comment by johnstevenson** [comment]
Finally released:
[v4.1.0](https://github.com/composer/windows-setup/releases/tag/v4.1.0)
