### ISSUE TITLE
Getting error when installing: "the program can't start because fbclient.dll is missing"

### ISSUE THREAD

**Issue by xpvenom** [composer/windows-setup#52]
When I run Composer-Setup.exe in windows 7 with php 7.0 I get the error "the program can't start because fbclient.dll is missing"

Please help.

**Comment by johnstevenson** [comment]
You need to configure php7 to work correctly. If it's a wamp installation this might help: http://stackoverflow.com/questions/12027614/php-cant-load-some-libraries
Otherwise you need to do some googling (like I just did).

**Comment by xpvenom** [comment]
@johnstevenson I installed PHP for IIS through the windows web platform. Trust me I've been googling.

**Comment by johnstevenson** [comment]
Okay, I downloaded the web platform installer, installed PHP7 and Composer-Setup works fine and installs composer. So there is something wrong with your php configuration.

Did Composer-Setup give you any clues, like telling you where your `php.ini` is located and that the extension_dir value might need checking?

**Comment by johnstevenson** [comment]
Presumably this has been resolved, so closing

**Comment by xpvenom** [comment]
I disabled the extensions that were giving me .dll errors through PHP manager in IIS and composer installed.

**Comment by johnstevenson** [comment]
Thanks for the info. If you can remember, did Composer-Setup give you any clues, like telling you where your php.ini is located and that the extension_dir value might need checking?
