### ISSUE TITLE
Your PATHEXT environment variable is missing a required value:       .BAT

### ISSUE THREAD

**Issue by hoverboardreviews** [composer/windows-setup#54]
Get this error when trying to install the program:

Your PATHEXT environment variable is missing a required value:
      .BAT

**Comment by johnstevenson** [comment]
You'll be needing that to run composer globally. Your System PathExt variable normally looks like this:
`.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`

However, if you have a PathExt variable in your User environment (even if it is an empty value) this will take precendence. Solution: Delete the user PathExt if you have one, or add `.BAT` to your System PathExt.

**Comment by johnstevenson** [comment]
In addition to the above, I recall that ruby once did this to me. If so, you'll have to merge whatever is in your User PathExt into the System one.

**Comment by TiaossuP** [comment]
thanks for @johnstevenson,   
I tried it and it's useful sure enough.  
And i just add `.BAT` to my **User PathExt** but not **System PathExt**.

**Comment by johnstevenson** [comment]
@TiaossuP That's fine unless you want to use something in your System PathExt that is not in your User PathExt (`.js`, `.vbs` etc). Modifying the System one and deleting the User one is more robust.

**Comment by hoverboardreviews** [comment]
I just added it like mentioned and was able to get it installed.

**Comment by dustinkingen** [comment]
My user level `PATHEXT` is set to `%PATHEXT%;.RB;.RBW`.

My system level `PATHEXT` is set to `.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC`.

The `Composer-Setup.msi` does not handle this case.

**Comment by johnstevenson** [comment]
Sorry, yes it doesn't handle this. The rubyinstaller used to add just `.RB;.RBW`, which was why Composer-Setup checked. I'll get this fixed.

**Comment by purexo** [comment]
I've this message but :
C:\wamp64\www\TDPHP\td1>echo %PATHEXT%
.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.RB;.RBW

**Comment by stevyhacker** [comment]
I've got this issue as well. I had .BAT added to my system level PATHEXT but it was not set to user PATHEXT, you just need to add it there as well.

**Comment by johnstevenson** [comment]
@stevyhacker Just add the ruby stuff to your System PathExt, then delete the User PathExt - this is what the rubyinstaller really should have done.

**Comment by johnstevenson** [comment]
Fixed in [latest release](https://github.com/johnstevenson/composer-setup/releases/latest)
