### ISSUE TITLE
Composer on Windows 10

### ISSUE THREAD

**Issue by heiz03** [composer/windows-setup#55]
Hi,

When I downloaded "Download and run Composer-Setup.exe - it will install the latest composer version whenever it is executed.", and installed it. For some reason I don't have an option for Shell menus.

Help please?

**Comment by alcohol** [comment]
This option was removed as far as I know.

**Comment by johnstevenson** [comment]
Yes, the shell menus have been removed. Try:

- Shift right-click: `Open command window here`
- with Git for Windows: `Git Bash Here`.
