### ISSUE TITLE
Windows installer does not prompt for install location 

### ISSUE THREAD

**Issue by ofbeaton** [composer/windows-setup#57]
Just went through the latest windows installer and it did not allow me to select an installation directory.

It went to `C:\ProgramData\ComposerSetup\bin` but this is not where I would have liked to install composer. The installer should provide a way to specify this, like the vast majority of windows installers do.

**Comment by johnstevenson** [comment]
Sorry, this is non-negotiable, as per the [README](https://github.com/composer/windows-setup/blob/master/README.md). It just makes life easier.

If the location matters to you that much, then you probably don't need to use this installer anyway.

**Comment by ofbeaton** [comment]
It's your program, so you can of course do as you like. However this is a standard feature of any installer I have ever used, I can't remember the last time a program didn't give me this option.

It may make your life easier (the maintainer), but it makes my life harder (the user). As is usually the case, it is a trade-off.

As a user I would like it. It sounds like you've already made up your mind and it is non-negotiable, while not a choice I agree with, this is your prerogative.

**Comment by johnstevenson** [comment]
Okay, this is the first time this has come up as an issue and it has obviously grated with you, so perhaps you could explain how it makes your life harder? Where would you prefer it install to (ie what are your requirements)?

**Comment by ofbeaton** [comment]
`this is non-negotiable` is pretty strong language, though not wrong. Text is hard, I am not angry, just inconvenienced and I am reporting it as such, especially for a feature I see in every other program installer. 

My requirement is to store Composer on a different drive, where I store all my development stuff. e.g. `D:\dev\composer`.

**Comment by tinelps** [comment]
Hi there, may i know how do i install this to my C:\ProgramData\ComposerSetup\bin ? I am new and do not know which file to click.

**Comment by johnstevenson** [comment]
What do you mean? It does install some stuff to `C:\ProgramData\ComposerSetup\bin`. May the [README](https://github.com/composer/windows-setup/blob/master/README.md) will help.

**Comment by tinelps** [comment]
@johnstevenson hi，i mean, how do i install it? as i don't have a `C:\ProgramData\ComposerSetup\bin` directory in my pc. Can u please help me?
What I mean is, i have download the file, and extract it at my `download` folder. But i don't know what to do next, what file to click to install?

**Comment by tinelps** [comment]
Hi @johnstevenson , so sorry i overlook the `Download` link ( `https://github.com/composer/windows-setup/releases/tag/v4.5.0` ).
My issue is solved, i have the `C:\ProgramData\ComposerSetup` and `C:\ProgramData\ComposerSetup\bin` now in my pc. Thanks alot!

**Comment by johnstevenson** [comment]
@ofbeaton I've kept this open until I had the opportunity to revisit the issue of a user-selected installation location. I modified the installer to allow this, but after much experimentation I have come to the conclusion that the original design decision is the most suitable.

Composer needs a place to perform its self-updates and this must be a writable location. For an admin install this needs to be accessible to all users (so `%ProgramData%` is the obvious and recommended choice). So if you used the modified installer you would end up with:

*  `D:\dev\composer` containing the ComposerSetup uninstall data and exe
* `C:\ProgramData\ComposerSetup` containing composer.phar and the shim scripts

which I guess is not doing what you would really wanted it to do.

I've added a short explanation to the read.me and removed the inflamatory `non-negotiable` wording!

**Comment by ofbeaton** [comment]
Thank you for taking the time to revisit and explore this. You're right, that isn't what I meant. 

If I told the installer to use `D:\dev\composer` I would expect all files there. For example `D:\dev\composer\bin` would then contain the phar. So the same as `C:\ProgramData\ComposerSetup\bin` except be able to replace the `C:\ProgramData\ComposerSetup` part of the path with whatever I wished.

You would still be able to structure the project however you wishes within that directory.

But perhaps you are installing things in multiple places already, which is leading to our misunderstanding here?

**Comment by johnstevenson** [comment]
> If I told the installer to use D:\dev\composer I would expect all files there. 

Unfortunately that is not possible because we always need to use `%ProgramData%` (or `%LocalAppData%`) to provide the guaranteed writable location. 

> But perhaps you are installing things in multiple places already, which is leading to our misunderstanding here?

Well, for an admin install we use `Program Files` for the ComposerSetup uninstaller and `%ProgramData%` for the Composer stuff, if that is what you mean.

**Comment by ofbeaton** [comment]
If I'm using the installer, and tell it to install in a specific location, aren't I, as the administrator running in the installer, guaranteeing it will be writable? `%ProgramData%` is a fine default, I just wish I could specify an alternative.

It sounds like we understand each other. It's just a matter if this would be important enough to add as a feature. If I'm the only one asking for it, it's probably not worth more of your time, though it is odd that it is missing.

Thank you for taking the time to consider it. Feel free to close the ticket at your discretion and decision.

**Comment by johnstevenson** [comment]
> If I'm using the installer, and tell it to install in a specific location, aren't I, as the administrator running in the installer, guaranteeing it will be writable?

Sure, it will be writable for you, but you might not be the only user and if that is the case then it might not be writable for them. What if you selected `C:\Users\<user>\dev\composer`? The installer would have to check the location and then add write permissions for all users to that directory. And if it was going to do that, then it should probably ask *your* permission first.

It is precisely because of all these hoops you have to jump through to guarantee a persistent reliable location that `%ProgramData%` (or `%ALLUSERSPROFILE%` as it once was) exists. Of course in the old pre-UAC days everything was chucked into Program Files (or your Documents directory).

> It's just a matter if this would be important enough to add as a feature ... though it is odd that it is missing

Which is why I've taken the time to revisit it and explore the options again. I have already suggested what it would look like, and you agreed that it wasn't what you were expecting.

I hope this explains things.

**Comment by johnstevenson** [comment]
@ofbeaton Hi, I haven't given up yet.

I'm experimenting with offering a _portable mode_ installation, which would let you choose which folder to install to. The only difference is that it wouldn't include an uninstaller.

Do you think this would this be a good compromise?

**Comment by ofbeaton** [comment]
Yes, I think that would be more than acceptable. Thank you.

**Comment by johnstevenson** [comment]
Cool. We will see how it goes.

It should probably be called a _developer mode_ installation, since it will invariably add something to the PATH, so portable is a bit of a misnomer.

**Comment by johnstevenson** [comment]
It's your lucky day: [Composer-Setup.4.5.2.exe](https://s3-eu-west-1.amazonaws.com/johnstevenson/composer/Composer-Setup.4.5.2.exe)

This is a pre-release version for testing. Would you mind giving it a run, if you have time. Thanks.

**Comment by Seldaek** [comment]
@johnstevenson ping me when stable so I update it on the site :)

**Comment by johnstevenson** [comment]
[v4.6.0](https://github.com/composer/windows-setup/releases/tag/v4.6.0) includes a _Developer mode_ option, which just downloads the core files, without an uninstaller.

**Comment by ofbeaton** [comment]
Thank you for persevering and coming up a solution that I think is fantastic. Nobody wants an installer with a thousand choices to make, but I think this is worthwhile. Thank you.

**Comment by johnstevenson** [comment]
Your thanks are appreciated. I think it has ended up as fairly unobtrusive option.

**Comment by Seldaek** [comment]
@johnstevenson thanks, I updated to latest on getcomposer.org :)

**Comment by johnstevenson** [comment]
@Seldaek Thanks, and 4.7.0 should be out later today.  I had to wait that long to get 4.6.0 through the chocolatey approval process (several months) that I had forgotten about this release!

**Comment by Seldaek** [comment]
Heh ok, ping me when it's up for download.
