### ISSUE TITLE
Error when installing composer using windows installer

### ISSUE THREAD

**Issue by alfredhb** [composer/windows-setup#64]
The Composer installer script did not run correctly because composer.phar was not downloaded.
[Setup Log 2016-11-24 #007.txt](https://github.com/composer/windows-setup/files/612199/Setup.Log.2016-11-24.007.txt)

**Comment by johnstevenson** [comment]
Wow! Not sure why, but the following happens:

- cmd.exe runs php and captures its output in a text file in the installer's tmp directory.
- cmd.exe repeats this with another script, but there is no output.
- cmd.exe tries again, but the tmp directory no longer exists!

What has removed it? I don't log why there was no output in the second step, but perhaps the text file has been removed as well? Who knows...

**Comment by alfredhb** [comment]
here is the last attempt i did
[Setup Log 2016-11-24 #008.txt](https://github.com/composer/windows-setup/files/612247/Setup.Log.2016-11-24.008.txt)
maybe help with something, i dont know why is happening

**Comment by johnstevenson** [comment]
Something is stopping the installer from running. The last log shows that the process was terminated just after it started. Aggressive antivirus/security program, perhaps?

**Comment by alfredhb** [comment]
Well i dont sure, because my antivirus is comodo, i gonna desactivate it and try again

**Comment by alfredhb** [comment]
With my antivirus desactive here is th
[Setup Log 2016-11-24 #011.txt](https://github.com/composer/windows-setup/files/612274/Setup.Log.2016-11-24.011.txt)
e log

**Comment by johnstevenson** [comment]
I'll take more of a look tomorrow. Meanwhile, you could try this:

- empty your `...AppData\Local\Temp` folder (or as much of it as you can)
- run the installer until you get the error, but keep it open
- look in your temp folder for a directory name `is-....tmp` and open it

You should find `stdout.txt` and `stderr.txt` files in there. Could you copy and paste the contents of each.

**Comment by johnstevenson** [comment]
Any luck? I cannot see any logical reason for this collection of errors to be happening. Sorry.

**Comment by alfredhb** [comment]
i did and i get this file 
[Setup Log 2016-11-25 #002.txt](https://github.com/composer/windows-setup/files/613667/Setup.Log.2016-11-25.002.txt)
and create 3 folders
is-CBQM6.tmp
is-DT746.tmp
is-R1U88.tmp
the first and the last one has a file with name Composer-Setup.tmp
the second has folder call _isetup where i find a file call _setup64.tmp
and also the folder has check.php, compser and installer.php

**Comment by johnstevenson** [comment]
Okay, thanks. The folder of interest is the one with check.php etc in it. However, you need to run the installer until you get the error, then look in the folders (the log is only showing you getting as far as the very first welcome page)

**Comment by johnstevenson** [comment]
Closing, as no more info received.
