### ISSUE TITLE
composer won't install with php5.6

### ISSUE THREAD

**Issue by IntellectProductions** [composer/windows-setup#65]
I'm getting an error when running this setup program. It is saying a lot of dll's are missing. I had composer installed on php5.5, but I'm trying to get it installed with php5.6 since I had to upgrade my php version. I changed the path environment and am selecting php5.6, but it's still trying to find the dll's in my other php folder saying they can't be found like icuuc51.dll when php5.6 comes with icuuc57.dll.

What is going on here?

**Comment by johnstevenson** [comment]
No idea. But a log file will help to identify the issue: https://github.com/composer/windows-setup#troubleshooting

**Comment by johnstevenson** [comment]
I guess this had something to do with the ini file and `extension_dir` setting, but without any more info we will never know.
