### ISSUE TITLE
unable to install composer on windows server 2008

### ISSUE THREAD

**Issue by lordfariq** [composer/windows-setup#68]
Please help

Warning: PHP Startup: Unable to load dynamic library 'C:\xampp\php\ext\php_intl.dll' - %1 is not a valid Win32 application.
 in Unknown on line 0

**Comment by johnstevenson** [comment]
I'll guess at a 32 bit library being called from a 64 bit php.exe?

**Comment by johnstevenson** [comment]
Closing as no further information received.
