### ISSUE TITLE
Fail Composer execute (show quotes)

### ISSUE THREAD

**Issue by webadequate** [composer/windows-setup#70]
Hello again!

Second time to install:
> Composer is already installed in the following directory:
> C:\OpenServer\modules\php\PHP-7.1-x64
> 
> You must remove it first, if you want to continue this installation.
[Setup Log 2017-05-27 #001.txt](https://github.com/composer/windows-setup/files/1044956/Setup.Log.2017-05-27.001.txt)
[Setup Log 2017-06-01 #001.txt](https://github.com/composer/windows-setup/files/1044955/Setup.Log.2017-06-01.001.txt)

**Comment by johnstevenson** [comment]
Thanks. Is the first log, the very first time you ran the installer?

**Comment by webadequate** [comment]
Yes. First time installed.

**Comment by johnstevenson** [comment]
Okay, so the installer put the composer files in the default directory `C:\ProgramData\ComposerSetup\bin` but according to the second log the installer finds these files in: `C:\OpenServer\modules\php\PHP-7.1-x64`

So I guess you must have added these yourself at some point.

In a cmd window, type `where composer` (or in Git Bash, `which composer`) and show us the output.

**Comment by webadequate** [comment]
C:\Users\Adobe>where composer
C:\Users\Adobe\composer
C:\OpenServer\modules\php\PHP-7.1-x64\composer.bat
C:\ProgramData\ComposerSetup\bin\composer
C:\ProgramData\ComposerSetup\bin\composer.bat

**Comment by webadequate** [comment]
I donwload OpenServer solution (included composer)

**Comment by johnstevenson** [comment]
I guess that the OpenServer composer.bat is being used, so perhaps there is something strange in this.

You could try renaming it, so the `ComposerSetup\bin\composer.bat` gets used.

**Comment by webadequate** [comment]
I rename the bin folder in C:\ProgramData\ComposerSetup\bin

try:

> C:\Users\Adobe>C:\OpenServer\modules\php\PHP-7.1-x64\composer
> '""' is not recognized as an internal or external command,
> operable program or batch file.

**Comment by webadequate** [comment]
An interest behabior:
Openserver has conemu command line in package.
If i just open 

> C:\OpenServer\modules\conemu\ConEmu64.exe

I got the same
![image](https://cloud.githubusercontent.com/assets/1946769/26796778/d30c5656-4a54-11e7-8e32-7b5bfe327c7e.png)

But if I will start the server and open ConEmu via OpenServer:
![image](https://cloud.githubusercontent.com/assets/1946769/26796952/7fea678c-4a55-11e7-8a74-92d1d179e3ad.png)

It works:
![image](https://cloud.githubusercontent.com/assets/1946769/26796983/988ae456-4a55-11e7-895f-fa164c8ccd2d.png)

**Comment by johnstevenson** [comment]
So what happens when you do what I suggested (so we can perhaps resolve an issue with the installer)?

**Comment by webadequate** [comment]
If I right understod, i must to delete ComposerSetup folder and reinstall again?

**Comment by johnstevenson** [comment]
No, not at all. The idea was that you rename `C:\OpenServer\modules\php\PHP-7.1-x64\composer.bat` to something like `...\composer1.bat` then run `composer` from the command prompt.

Because the `composer.bat` in `C:\ProgramData\ComposerSetup\bin` is in your path, this should then get called.

However, you said you had renamed the `C:\ProgramData\ComposerSetup\bin` folder, so I don't really know how to help.

**Comment by webadequate** [comment]
Oh. It works!
![image](https://cloud.githubusercontent.com/assets/1946769/26799103/630786be-4a5e-11e7-95a1-45766014e679.png)

**Comment by webadequate** [comment]
composer1.bat:
`@"%PHP_BIN%" -d output_buffering=0 "%PHP_DIR%composer.phar" %* `

**Comment by johnstevenson** [comment]
Ah, so the `composer.bat` that was written by OpenServer requires that it is called with the `PHP_BIN` and `PHP_DIR` environment variables set, which only happens if you launch it through their console.

I'll close this as it has nothing to do with ComposerSetup.
