### ISSUE TITLE
Option to change PHP path

### ISSUE THREAD

**Issue by denisdulici** [composer/windows-setup#72]
It would be nice if there were an option to change the following option without having to uninstall => install:

![2017-07-05_1025](https://user-images.githubusercontent.com/5254835/27854040-e70181b0-616d-11e7-95fd-3d683606bd77.png)

This is crucial if you have multiple Xampp installations.

Refs https://github.com/composer/composer/issues/6277

**Comment by johnstevenson** [comment]
Sorry, but this is not an installer issue.

You need to change your PATH environment variable so that it includes the location of the version you want to use. You can use the Control Panel to do this, or you can do it from your shell.

(You can also run Composer Setup again, there is no need to uninstall first)

**Comment by denisdulici** [comment]
I didn't say it's an installer issue, the screenshot is to show that I'm not talking about Composer but PHP path.

Is there any doc that shows how and where to change this PATH ?

**Comment by johnstevenson** [comment]
Yes, it is called the internet.

**Comment by geeky3** [comment]
You can change php version of composer without uninstalling it, follow these steps :

1) Search for system environment variables in cortana.
2) Click on the button "Environment variables".
3) Under "System variables" select path and click on edit, you will see one entry like this "C:\wamp\bin\php\php5.6.13".
4) Just change this to the folder name of the php located at your wamp/bin/php7.1.9, here bin7.1.9 is folder name.
5) Replace php5.6.13 with bin7.1.9, it will look like these "C:\wamp\bin\php\php7.1.9", just click ok on all the boxes.
6) You are done.
7) To verify, first close all the cmd windows, than open cmd and type "php -v", press enter and you should see php7.1.9.
8) If you don't see change in php version than just restart your pc and run php -v again in cmd , it will work.

**Comment by Arikowid31** [comment]
thanks, i use this to change the php path, worked without typing the number version 👍
