### ISSUE TITLE
pass version to install

### ISSUE THREAD

**Issue by alcohol** [composer/windows-setup#73]
Hey, would it be a lot of work to support passing a specific version to install as one of the arguments to the installer/chocolatey?

**Comment by johnstevenson** [comment]
Not really.

I could introduce a command-line flag like `/VER=whatever` and pass this to the composer installer in the `--version` param. If the version doesn't exist then the installation will fail (ie there will be no user option to change the version).



Are you thinking about using chocolatey for CI?

**Comment by alcohol** [comment]
I'm just thinking from a user perspective, to allow for a more idempotent-like operation. As I understand it right now, you can only install the latest version, no matter when you run this installer.

**Comment by johnstevenson** [comment]
Composer-Setup installs the latest stable version (or rather it doesn't pass a `--version` or `--channel` param to the installer and relies on the current default behavior).

Adding a user-selectable version field over-complicates things, in my view. If the user is savvy enough to require a particular version (and they prefer use an exe installer) then they most likely have the sense to run `composer self-update --snapshot` afterwards.

Or perhaps I am missing something here.

**Comment by alcohol** [comment]
Well since the installer supports passing `--version`, I was just wondering if this installer can basically take the same argument and pass that on.

**Comment by alcohol** [comment]
But if it is more work than just a simple one-liner (or close to that), then never mind. It's not an issue :-)

**Comment by johnstevenson** [comment]
Well, the installer script also supports `--install-dir`, `--filename`, `--preview` and `--snapshot`. Should I support those as well?

I'm not being arsey, but this is an easy-to-use setup exe, that tries to make the experience as painless as possible for the user. I could add a new command-line flag, as I mentioned above, but how many normal users run an exe from the command-line?

Of course, there may well be a use for this, but I think I'd prefer to know what it is first, if that is okay with you.

**Comment by johnstevenson** [comment]
Those old comments about the first chocolatey package (which downloaded and ran Composer-Setup.exe from getcomposer.org) were not about being able to specify a version, rather that the writer was assuming that the chocolatey package version would be the version of Composer that would be installed (and that this was lower than the Composer version at that time).

If you're a sysadmin and you are using chocolatey, then you have a lot more to worry about than specific  Composer versions! Likewise, if you are a standard user.

**Comment by alcohol** [comment]
Alright, never mind then 👍

**Comment by johnstevenson** [comment]
If someone really needs this, then I can add it as a command-line option.
