### ISSUE TITLE
Composer requesting packagist authentication

### ISSUE THREAD

**Issue by Furqanaa** [composer/windows-setup#75]
I'm new to laravel & composer, I used composer to download laravel package, the composer is requesting an authentication for packagist.org:
`Installing laravel/laravel (v5.5.0)
  - Installing laravel/laravel (v5.5.0): Loading from cache
Created project in TestLaravel
> @php -r "file_exists('.env') || copy('.env.example', '.env');"
Loading composer repositories with package information
Updating dependencies (including require-dev)

    Authentication required (packagist.org):
      Username:
      Password:

  [Composer\Downloader\TransportException]
  The "http://packagist.org/p/fideloper/proxy%245475fc0d4379d08a55b6e256813b0
  223f779b1106292a3895064434bad3eb6a9.json" file could not be downloaded: fai
  led to open stream: A connection attempt failed because the connected party
   did not properly respond after a period of time, or established connection
   failed because connected host has failed to respond.

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--r
epository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no
-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vc
s] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<vers
ion>]
`
**I notice that I don't have a composer.json file in Users\MyUser\AppData\Roaming\Composer** 

I tried to add my packagist.org account to auth.json:
`  "http-basic": {"packagist.org": {
            "username": "my_account",
            "password": "my_password"
        }}` 
the composer did not requested authentication any more but i still have the following exception:
`Installing laravel/laravel (v5.5.0)
  - Installing laravel/laravel (v5.5.0): Loading from cache
Created project in TestLaravel
> @php -r "file_exists('.env') || copy('.env.example', '.env');"
Loading composer repositories with package information
Updating dependencies (including require-dev)

  [Composer\Downloader\TransportException]
  Invalid credentials for 'http://packagist.org/p/fideloper/proxy%245475fc0d4
  379d08a55b6e256813b0223f779b1106292a3895064434bad3eb6a9.json', aborting.

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--r
epository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no
-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vc
s] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<vers
ion>]
`
Please any idea on how to solve this ?

**Comment by johnstevenson** [comment]
This is a composer issue, rather than an installer one (Composer-Setup) and I'm guessing you are using a proxy.

Please Google for `Invalid credentials for 'http://packagist.org` and you will find a few reported issues that might solve your problem.

If not, then please report the issue in the main repo: https://github.com/composer/composer/issues/new

**Comment by Furqanaa** [comment]
@johnstevenson thank you very much

**Comment by johnstevenson** [comment]
@vsalguero This repo is for the Windows installer (Composer-Setup).

You need to report Composer issues on the main Composer repo:  https://github.com/composer/composer/issues/new
