### ISSUE TITLE
composer error

### ISSUE THREAD

**Issue by AhmedNoor96** [composer/windows-setup#82]
The Composer installer script did not run correctly [exit code 1]:

Warning: Module 'openssl' already loaded in Unknown on line 0
The "https://getcomposer.org/versions" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Failed to enable crypto
failed to open stream: operation failed

PHP Warning:  Module 'openssl' already loaded in Unknown on line 0

any help please!

**Comment by johnstevenson** [comment]
Your php.ini file includes extension openssl more than once. If you want any more help,  you must supply a log file, as requested when you created the issue:

>  Composer-Setup creates a log file in your temp directory AppData\Local\Temp, with a formatted filename:
    Setup Log YYYY-MM-DD #nnn.txt
  Please include this file if you experienced a problem with the installation process. Review it first
  for any data that might be sensitive.

**Comment by johnstevenson** [comment]
Closing, as no further info has been provided.
