### ISSUE TITLE
Cannot install Composer using Windows installer

### ISSUE THREAD

**Issue by sreekanth2201** [composer/windows-setup#83]
Hi John,
I am unable to install composer using the windows installer(composer.exe) on windows 7(32 bit).
I am getting the following message when try to run the exe.

```
The PHP exe file you specified did not run correctly [exit code 1]:
C:\xampp\php\php.exe

The php.ini used by your command-line PHP is: C:\xampp\php\php.ini

No output was returned.
```

It seems that the script is unable to run php.exe from command line
I have added the path for php in Environment Variables.
Please view the attached error log.

Checked the previous issue for solution
No ANSICON is installed in the system.
However found ANSI.SYS on windows\system32
I checked the following issues:
[https://github.com/composer/composer/issues/3324](url)
[https://github.com/composer/windows-setup/issues/74](url)

But no fix. Can you provide a solution for the same?

[Setup Log 2017-11-29 #011.txt](https://github.com/composer/windows-setup/files/1514982/Setup.Log.2017-11-29.011.txt)

Regards,
Sreekanth

**Comment by johnstevenson** [comment]
Try using the latest version (4.8.0). It was only updated on getcomposer.org yesterday:
https://getcomposer.org/Composer-Setup.exe

It does a better job of handling this sort of thing, so it might give you a bit more information

**Comment by sreekanth2201** [comment]
Hi John,
Thank you very much. It resolved the issue.
The 4.7 version was not updated as per the previous issue for the same.

**Comment by johnstevenson** [comment]
@sreekanth2201 Great. What was the issue and how did the latest version help?

**Comment by sreekanth2201** [comment]
@johnstevenson  I think the script cancelled without giving any error message. 
From the logs of the older exe, the script exited with the message "Success: exit code [1]" whereas while in the new log, the script ran with the message "Success: exit code [0]".

Please view the attached log below:
[Setup Log 2017-11-30 #001.txt](https://github.com/composer/windows-setup/files/1518854/Setup.Log.2017-11-30.001.txt)

Also given the log of earlier version below:
[Setup Log 2017-11-29 #010.txt](https://github.com/composer/windows-setup/files/1518855/Setup.Log.2017-11-29.010.txt)

I am new to composer. I would appreciate if you could compare the logs and let me know what was causing the issue.

Thanks,
Sreekanth

**Comment by johnstevenson** [comment]
@sreekanth2201 Thanks for the info. Unfortunately I am no wiser, since I expected the current Composer-Setup to provide a better error message, but instead there was no error (exit code 0). Unless you changed something (removed ANSI.SYS perhaps), then I am afraid I have no idea.

Don't worry about using composer: Composer-Setup is just an installer and it is mainly concerned with command-line PHP being set up correctly (which it now seems to be).

**Comment by johnstevenson** [comment]
Composer-Setup called `C:\Windows\system32\cmd.exe` in both cases. Perhaps you had some config setting that then invoked Cygwin. Who knows.

If you wanted, you could run the [4.7.0](https://github.com/composer/windows-setup/releases/download/v4.7.0/Composer-Setup.4.7.0.exe) version again and see what happens.

**Comment by sreekanth2201** [comment]
Hi John,

I will be installing composer on windows server later. I will check the log
then and let you know if there is any issue with the installer.

Thank you.

**Comment by inayath123** [comment]
I have windows 10 with xampp 3.0.12 (php5.4). I was not able to install composer. I tried below steps it worked for me.
1. download installer script from https://getcomposer.org/installer
2. save it in a file called as composer-setup.php
3. open composer-setup.php in vscode or subline code editor.
4. replace all https to http and save file.
5.  execute below 3 steps in command prompt.

php -r "if (hash_file('sha384', 'composer-setup.php') === 'a5c698ffe4b8e849a443b120cd5ba38043260d5c4023dbf93e1558871f1f07f58274fc6f4c93bcfd858c6bd0775cd8d1') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"

php composer-setup.php

php -r "unlink('composer-setup.php');"

6. viola! successfully installed composer, you can run: php composer.phar.

Thanks

**Comment by johnstevenson** [comment]
@inayath123 Your instructions are nonsense:

If you edit the downloaded installer (named as composer-setup.php) then the first command to verify this file is never going to work and composer-setup.php will be deleted.

Also, having to edit the installer means that there is probably something wrong with your php configuration. It might have been better to create an issue here so we could have analyzed your setup log to solve the problem.

**Comment by naveenkumarit2** [comment]
Change your network or proxy settings that will resolve issue.

**Comment by Uniqueeunice** [comment]
The Composer installer script was not successful [exit code 1].

@Uniqueeunice 
this is the error i'm getting trying to install composer-setup.exe in windows 10, what could be the solution...

Unable to continue with the installation
 Script Output:
The "https://getcomposer.org/versions" file could not be downloaded: php_network_getaddresses: getaddrinfo for getcomposer.org failed: No such host is known.
