### ISSUE TITLE
# We are in Cygwin using Windows php, so the path must be translated

### ISSUE THREAD

**Issue by Eugene-Melbourne** [composer/windows-setup#93]
in my vagrant@homestead:/tmp$ ls
was no directory like directory AppData\Local\Temp

please help if you can

https://stackoverflow.com/questions/56105111/laravel-homestead-per-project-installation-make-error

**Comment by johnstevenson** [comment]
We need a log file as per the instructions: https://github.com/composer/windows-setup/issues/new

**Comment by johnstevenson** [comment]
Log file not supplied.
