### ISSUE TITLE
SSL operation failed with code 1. OpenSSL Error messages

### ISSUE THREAD

**Issue by seanounruan** [composer/windows-setup#95]
I was install Composer on a fresh new installed of Windows 10 Pro build 1809 and I got this error message.

`The Composer installer script was not successful [exit code 1].`
`OpenSSL failed with a 'certificate verify failed' error. This indicates a problem with the Certificate Authority file(s) on your system, which may be out of date.`

`Certificate location [from openssl.cafile ini setting]:`
`D:\xampp\apache\bin\curl-ca-bundle.crt`

`The php.ini used by your command-line PHP is: D:\xampp\php\php.ini`

`Script Output:`
`The "https://getcomposer.org/versions" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:`
`error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed`
`Failed to enable crypto`
`failed to open stream: operation failed`

So, I've tried to replace the "curl-ca-bundle.crt" with "cacert.pem" from http://curl.haxx.se/ca/cacert but it's nothing happened the error messages still happened.

Can anyone help me to fix this problem?

Here is all my setup logs:
[Setup Log 2019-06-12 #001.txt](https://github.com/composer/windows-setup/files/3280723/Setup.Log.2019-06-12.001.txt)
[Setup Log 2019-06-12 #002.txt](https://github.com/composer/windows-setup/files/3280725/Setup.Log.2019-06-12.002.txt)
[Setup Log 2019-06-12 #003.txt](https://github.com/composer/windows-setup/files/3280727/Setup.Log.2019-06-12.003.txt)
[Setup Log 2019-06-12 #004.txt](https://github.com/composer/windows-setup/files/3280728/Setup.Log.2019-06-12.004.txt)
[Setup Log 2019-06-12 #005.txt](https://github.com/composer/windows-setup/files/3280729/Setup.Log.2019-06-12.005.txt)
[Setup Log 2019-06-12 #006.txt](https://github.com/composer/windows-setup/files/3280730/Setup.Log.2019-06-12.006.txt)
[Setup Log 2019-06-12 #007.txt](https://github.com/composer/windows-setup/files/3280732/Setup.Log.2019-06-12.007.txt)
[Setup Log 2019-06-12 #008.txt](https://github.com/composer/windows-setup/files/3280734/Setup.Log.2019-06-12.008.txt)
[Setup Log 2019-06-12 #009.txt](https://github.com/composer/windows-setup/files/3280735/Setup.Log.2019-06-12.009.txt)
[Setup Log 2019-06-12 #010.txt](https://github.com/composer/windows-setup/files/3280736/Setup.Log.2019-06-12.010.txt)
[Setup Log 2019-06-12 #011.txt](https://github.com/composer/windows-setup/files/3280720/Setup.Log.2019-06-12.011.txt)

**Comment by johnstevenson** [comment]
I cannot reproduce this using a fresh install of xampp (using php 7.3.6 like yours), which includes this `curl-ca-bundle.crt`:

```##
## Bundle of CA Root Certificates
##
## Certificate data from Mozilla as of: Wed May 15 03:12:09 2019 GMT
...
```

**Comment by seanounruan** [comment]
Before this fresh install I was on Windows 10 build 1903 and xampp with PHP 7.1. I've try many solution to fixed it. After that I've re-install a new Windows 10 build 1809 and install a new version of xampp with php 7.3.6

So, I've attached a curl-ca-bundle.crt:
[curl-ca-bundle.zip](https://github.com/composer/windows-setup/files/3284049/curl-ca-bundle.zip)

**Comment by johnstevenson** [comment]
That looks like the same bundle - perhaps something else is getting in the way (like anti-virus). Try commenting out the ini entry, by prepending a semi-colon:

```
File: D:\xampp\php\php.ini
 
;openssl.cafile=D:\xampp\apache\bin\curl-ca-bundle.crt
```
This will force the installer script to use its own certificate bundle instead.

**Comment by seanounruan** [comment]
I was commented that line out and turned Windows Security off. It didn't work.

Still got the same error:

```
The Composer installer script was not successful [exit code 1].

OpenSSL failed with a 'certificate verify failed' error. This indicates a problem with the Certificate Authority file(s) on your system, which either cannot be found or may be out of date.

Script Output:
The "https://getcomposer.org/versions" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
Failed to enable crypto
failed to open stream: operation failed
```

**Comment by seanounruan** [comment]
Finally, I solved this problem. Because my company's blocked something on the network. Then I try to switched to the other network It's succuessful! THANKS a lot for you help.

**Comment by siberakunesia** [comment]
Finally, I solved this problem, by deactive anti virus.

**Comment by QuietCodeJourney** [comment]
> I was commented that line out and turned Windows Security off. It didn't work.
> 
> Still got the same error:

it works

**Comment by Ateeq44** [comment]
fucking solution

**Comment by mitkonikov** [comment]
I still have this issue. I could only install Composer manually via the `phar` file. The installer fails even if I disable both my Antiviruses and/or add the latest SSL certificates. I checked the Root Certificate I have on Windows and tried to download the latest certs from `curl` but nothing.
