### ISSUE TITLE
unable to install composer manually in wamp64

### ISSUE THREAD

**Issue by Jael07** [composer/windows-setup#98]
Hi

Tried to install composer manually in below procedure

1.Set the path variable with the location where php.exe exists
2.Downloaded latest composer.phar , copied that in php.exe location
3. Tried to run echo @php "%~dp0composer.phar" %*>composer.bat in the same php.exe path in command prompt
4.Closed that command window again reopened command window with same path tried to give command **composer -V**
 Then i observed the following error

**could not open input file : E:/wamp64/bin/php/php7.1.9/composer -V**

could you please help me with this.

**Comment by Jael07** [comment]
Thank you 

But I don't have internet connection in my desktop.
While installing it is asking for proxy

So how could i Avoid this???

**Comment by Jael07** [comment]
No I'm not using any proxy. so what should i do now??

**Comment by johnstevenson** [comment]
Click the Next button and move on to the next page.

**Comment by johnstevenson** [comment]
If you need more help, there are plenty of video tutorials around. Here is one that I found: https://www.youtube.com/watch?v=HBDJsc2cXR4

**Comment by Jael07** [comment]
![image](https://user-images.githubusercontent.com/54095094/63588838-17cc3980-c5c5-11e9-9cec-645e6a50cd35.png)


i found this error when i tried to install as shown in video

**Comment by johnstevenson** [comment]
So you are not connected to the internet then?

If this is the case, why are you trying to install Composer? Do you realize that Composer needs the internet to download the packages you require?

It might help if you can explain exactly what you are trying to do.

**Comment by Jael07** [comment]
I think i told you earlier that i tried to install composer manually as i don't have internet connected to my PC ( i mean i want composer to be installed offline) For the same i tried 

![image](https://user-images.githubusercontent.com/54095094/63667113-32362b00-c7f0-11e9-8e75-1f9d58e2446d.png)



So could you please help me with the installation

**Comment by johnstevenson** [comment]
Okay. I only suggested using the installer because it provides a log, which can help track down problems. 

Otherwise, we're jusy blindly guessing at what you, or your system have done wrong. Sorry.
