### ISSUE TITLE
Unable to install composer offline manually (composer.phar)

### ISSUE THREAD

**Issue by Jael07** [composer/windows-setup#99]
Hi

Tried to install composer manually in below procedure

1.Set the path variable with the location where php.exe exists
2.Downloaded latest composer.phar , copied that in php.exe location
3. Tried to run echo @php "%~dp0composer.phar" %*>composer.bat in the same php.exe path in command prompt
4.Closed that command window again reopened command window with same path tried to give command composer -V
Then i observed the following error

could not open input file : E:/wamp64/bin/php/php7.1.9/composer -V

could you please help me with this.

**Comment by johnstevenson** [comment]
As I stated in the previous issue #98 , if you cannot use the windows installer then it makes it very difficult to find out what has gone wrong.

There are plenty of You Tube videos about installing Composer on Windows, and not all of these make use of Composer-Setup: perhaps one of these may help you spot what you have done wrong.

There are also some old notes in this repo about installing manually: https://github.com/composer/windows-setup/wiki/Manual-installation This explains how to use php from the command-line
 and takes you through each step of installing and setting up Composer.

**Comment by johnstevenson** [comment]
Closing, as no further comments.
